// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: error_message.proto
// Protobuf C++ Version: 6.31.0

#ifndef error_5fmessage_2eproto_2epb_2eh
#define error_5fmessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_error_5fmessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_error_5fmessage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_error_5fmessage_2eproto;
}  // extern "C"
enum EM_Type : int;
extern const uint32_t EM_Type_internal_data_[];
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EM_Type_internal_data_>
    internal::EnumTraitsImpl::value<::EM_Type>;
}  // namespace protobuf
}  // namespace google

enum EM_Type : int {
  EM_UNSPECIFIED = 0,
  EM_DISCONNECTED = 1,
  EM_ENDOFFILE = 2,
  EM_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  EM_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t EM_Type_internal_data_[];
inline constexpr EM_Type EM_Type_MIN =
    static_cast<EM_Type>(0);
inline constexpr EM_Type EM_Type_MAX =
    static_cast<EM_Type>(2);
inline bool EM_Type_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int EM_Type_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EM_Type_descriptor();
template <typename T>
const ::std::string& EM_Type_Name(T value) {
  static_assert(::std::is_same<T, EM_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EM_Type_Name().");
  return EM_Type_Name(static_cast<EM_Type>(value));
}
template <>
inline const ::std::string& EM_Type_Name(EM_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EM_Type_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool EM_Type_Parse(
    ::absl::string_view name, EM_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EM_Type>(EM_Type_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EM_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EM_Type>() {
  return ::EM_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // error_5fmessage_2eproto_2epb_2eh
