// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game_message.proto
// Protobuf C++ Version: 6.31.0

#ifndef game_5fmessage_2eproto_2epb_2eh
#define game_5fmessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_game_5fmessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_game_5fmessage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_game_5fmessage_2eproto;
}  // extern "C"
enum PGM_Type : int;
extern const uint32_t PGM_Type_internal_data_[];
class PGM_RequestSync;
struct PGM_RequestSyncDefaultTypeInternal;
extern PGM_RequestSyncDefaultTypeInternal _PGM_RequestSync_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PGM_RequestSync_class_data_;
class PGM_RequestSyncResult;
struct PGM_RequestSyncResultDefaultTypeInternal;
extern PGM_RequestSyncResultDefaultTypeInternal _PGM_RequestSyncResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PGM_RequestSyncResult_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::PGM_Type_internal_data_>
    internal::EnumTraitsImpl::value<::PGM_Type>;
}  // namespace protobuf
}  // namespace google

enum PGM_Type : int {
  PGM_UNSPECIFIED = 0,
  STM_EVENT_1 = 1,
  STM_EVENT_2 = 2,
  PGM_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PGM_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PGM_Type_internal_data_[];
inline constexpr PGM_Type PGM_Type_MIN =
    static_cast<PGM_Type>(0);
inline constexpr PGM_Type PGM_Type_MAX =
    static_cast<PGM_Type>(2);
inline bool PGM_Type_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int PGM_Type_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PGM_Type_descriptor();
template <typename T>
const ::std::string& PGM_Type_Name(T value) {
  static_assert(::std::is_same<T, PGM_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PGM_Type_Name().");
  return PGM_Type_Name(static_cast<PGM_Type>(value));
}
template <>
inline const ::std::string& PGM_Type_Name(PGM_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PGM_Type_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool PGM_Type_Parse(
    ::absl::string_view name, PGM_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PGM_Type>(PGM_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PGM_RequestSyncResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PGM_RequestSyncResult) */ {
 public:
  inline PGM_RequestSyncResult() : PGM_RequestSyncResult(nullptr) {}
  ~PGM_RequestSyncResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PGM_RequestSyncResult* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PGM_RequestSyncResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PGM_RequestSyncResult(::google::protobuf::internal::ConstantInitialized);

  inline PGM_RequestSyncResult(const PGM_RequestSyncResult& from) : PGM_RequestSyncResult(nullptr, from) {}
  inline PGM_RequestSyncResult(PGM_RequestSyncResult&& from) noexcept
      : PGM_RequestSyncResult(nullptr, ::std::move(from)) {}
  inline PGM_RequestSyncResult& operator=(const PGM_RequestSyncResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline PGM_RequestSyncResult& operator=(PGM_RequestSyncResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PGM_RequestSyncResult& default_instance() {
    return *reinterpret_cast<const PGM_RequestSyncResult*>(
        &_PGM_RequestSyncResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PGM_RequestSyncResult& a, PGM_RequestSyncResult& b) { a.Swap(&b); }
  inline void Swap(PGM_RequestSyncResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PGM_RequestSyncResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PGM_RequestSyncResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PGM_RequestSyncResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PGM_RequestSyncResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PGM_RequestSyncResult& from) { PGM_RequestSyncResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PGM_RequestSyncResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PGM_RequestSyncResult"; }

 protected:
  explicit PGM_RequestSyncResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PGM_RequestSyncResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PGM_RequestSyncResult& from);
  PGM_RequestSyncResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PGM_RequestSyncResult&& from) noexcept
      : PGM_RequestSyncResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSequenceNumberFieldNumber = 1,
  };
  // int32 sequenceNumber = 1;
  bool has_sequencenumber() const;
  void clear_sequencenumber() ;
  ::int32_t sequencenumber() const;
  void set_sequencenumber(::int32_t value);

  private:
  ::int32_t _internal_sequencenumber() const;
  void _internal_set_sequencenumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PGM_RequestSyncResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PGM_RequestSyncResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t sequencenumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PGM_RequestSyncResult_class_data_;
// -------------------------------------------------------------------

class PGM_RequestSync final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PGM_RequestSync) */ {
 public:
  inline PGM_RequestSync() : PGM_RequestSync(nullptr) {}
  ~PGM_RequestSync() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PGM_RequestSync* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PGM_RequestSync));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PGM_RequestSync(::google::protobuf::internal::ConstantInitialized);

  inline PGM_RequestSync(const PGM_RequestSync& from) : PGM_RequestSync(nullptr, from) {}
  inline PGM_RequestSync(PGM_RequestSync&& from) noexcept
      : PGM_RequestSync(nullptr, ::std::move(from)) {}
  inline PGM_RequestSync& operator=(const PGM_RequestSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline PGM_RequestSync& operator=(PGM_RequestSync&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PGM_RequestSync& default_instance() {
    return *reinterpret_cast<const PGM_RequestSync*>(
        &_PGM_RequestSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PGM_RequestSync& a, PGM_RequestSync& b) { a.Swap(&b); }
  inline void Swap(PGM_RequestSync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PGM_RequestSync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PGM_RequestSync* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PGM_RequestSync>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PGM_RequestSync& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PGM_RequestSync& from) { PGM_RequestSync::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PGM_RequestSync* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PGM_RequestSync"; }

 protected:
  explicit PGM_RequestSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PGM_RequestSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PGM_RequestSync& from);
  PGM_RequestSync(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PGM_RequestSync&& from) noexcept
      : PGM_RequestSync(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSequenceNumberFieldNumber = 1,
  };
  // int32 sequenceNumber = 1;
  bool has_sequencenumber() const;
  void clear_sequencenumber() ;
  ::int32_t sequencenumber() const;
  void set_sequencenumber(::int32_t value);

  private:
  ::int32_t _internal_sequencenumber() const;
  void _internal_set_sequencenumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PGM_RequestSync)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PGM_RequestSync& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t sequencenumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PGM_RequestSync_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PGM_RequestSync

// int32 sequenceNumber = 1;
inline bool PGM_RequestSync::has_sequencenumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PGM_RequestSync::clear_sequencenumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PGM_RequestSync::sequencenumber() const {
  // @@protoc_insertion_point(field_get:PGM_RequestSync.sequenceNumber)
  return _internal_sequencenumber();
}
inline void PGM_RequestSync::set_sequencenumber(::int32_t value) {
  _internal_set_sequencenumber(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PGM_RequestSync.sequenceNumber)
}
inline ::int32_t PGM_RequestSync::_internal_sequencenumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequencenumber_;
}
inline void PGM_RequestSync::_internal_set_sequencenumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = value;
}

// -------------------------------------------------------------------

// PGM_RequestSyncResult

// int32 sequenceNumber = 1;
inline bool PGM_RequestSyncResult::has_sequencenumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PGM_RequestSyncResult::clear_sequencenumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PGM_RequestSyncResult::sequencenumber() const {
  // @@protoc_insertion_point(field_get:PGM_RequestSyncResult.sequenceNumber)
  return _internal_sequencenumber();
}
inline void PGM_RequestSyncResult::set_sequencenumber(::int32_t value) {
  _internal_set_sequencenumber(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PGM_RequestSyncResult.sequenceNumber)
}
inline ::int32_t PGM_RequestSyncResult::_internal_sequencenumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequencenumber_;
}
inline void PGM_RequestSyncResult::_internal_set_sequencenumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::PGM_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::PGM_Type>() {
  return ::PGM_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // game_5fmessage_2eproto_2epb_2eh
