// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game_message.proto
// Protobuf C++ Version: 6.31.0

#ifndef game_5fmessage_2eproto_2epb_2eh
#define game_5fmessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_game_5fmessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_game_5fmessage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_game_5fmessage_2eproto;
}  // extern "C"
enum GM_Type : int;
extern const uint32_t GM_Type_internal_data_[];
class GM_RequestSync;
struct GM_RequestSyncDefaultTypeInternal;
extern GM_RequestSyncDefaultTypeInternal _GM_RequestSync_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GM_RequestSync_class_data_;
class GM_RequestSyncResult;
struct GM_RequestSyncResultDefaultTypeInternal;
extern GM_RequestSyncResultDefaultTypeInternal _GM_RequestSyncResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GM_RequestSyncResult_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::GM_Type_internal_data_>
    internal::EnumTraitsImpl::value<::GM_Type>;
}  // namespace protobuf
}  // namespace google

enum GM_Type : int {
  GM_UNSPECIFIED = 0,
  GM_DISCONNECTED = 300,
  STM_EVENT_1 = 301,
  STM_EVENT_2 = 302,
  GM_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GM_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GM_Type_internal_data_[];
inline constexpr GM_Type GM_Type_MIN =
    static_cast<GM_Type>(0);
inline constexpr GM_Type GM_Type_MAX =
    static_cast<GM_Type>(302);
inline bool GM_Type_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, GM_Type_internal_data_);
}
inline constexpr int GM_Type_ARRAYSIZE = 302 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GM_Type_descriptor();
template <typename T>
const ::std::string& GM_Type_Name(T value) {
  static_assert(::std::is_same<T, GM_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to GM_Type_Name().");
  return ::google::protobuf::internal::NameOfEnum(GM_Type_descriptor(), value);
}
inline bool GM_Type_Parse(
    ::absl::string_view name, GM_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GM_Type>(GM_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class GM_RequestSyncResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GM_RequestSyncResult) */ {
 public:
  inline GM_RequestSyncResult() : GM_RequestSyncResult(nullptr) {}
  ~GM_RequestSyncResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GM_RequestSyncResult* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GM_RequestSyncResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GM_RequestSyncResult(::google::protobuf::internal::ConstantInitialized);

  inline GM_RequestSyncResult(const GM_RequestSyncResult& from) : GM_RequestSyncResult(nullptr, from) {}
  inline GM_RequestSyncResult(GM_RequestSyncResult&& from) noexcept
      : GM_RequestSyncResult(nullptr, ::std::move(from)) {}
  inline GM_RequestSyncResult& operator=(const GM_RequestSyncResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline GM_RequestSyncResult& operator=(GM_RequestSyncResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GM_RequestSyncResult& default_instance() {
    return *reinterpret_cast<const GM_RequestSyncResult*>(
        &_GM_RequestSyncResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GM_RequestSyncResult& a, GM_RequestSyncResult& b) { a.Swap(&b); }
  inline void Swap(GM_RequestSyncResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GM_RequestSyncResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GM_RequestSyncResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GM_RequestSyncResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GM_RequestSyncResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GM_RequestSyncResult& from) { GM_RequestSyncResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GM_RequestSyncResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GM_RequestSyncResult"; }

 protected:
  explicit GM_RequestSyncResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GM_RequestSyncResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GM_RequestSyncResult& from);
  GM_RequestSyncResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GM_RequestSyncResult&& from) noexcept
      : GM_RequestSyncResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSequenceNumberFieldNumber = 1,
  };
  // int32 sequenceNumber = 1;
  bool has_sequencenumber() const;
  void clear_sequencenumber() ;
  ::int32_t sequencenumber() const;
  void set_sequencenumber(::int32_t value);

  private:
  ::int32_t _internal_sequencenumber() const;
  void _internal_set_sequencenumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GM_RequestSyncResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GM_RequestSyncResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t sequencenumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GM_RequestSyncResult_class_data_;
// -------------------------------------------------------------------

class GM_RequestSync final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GM_RequestSync) */ {
 public:
  inline GM_RequestSync() : GM_RequestSync(nullptr) {}
  ~GM_RequestSync() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GM_RequestSync* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GM_RequestSync));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GM_RequestSync(::google::protobuf::internal::ConstantInitialized);

  inline GM_RequestSync(const GM_RequestSync& from) : GM_RequestSync(nullptr, from) {}
  inline GM_RequestSync(GM_RequestSync&& from) noexcept
      : GM_RequestSync(nullptr, ::std::move(from)) {}
  inline GM_RequestSync& operator=(const GM_RequestSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline GM_RequestSync& operator=(GM_RequestSync&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GM_RequestSync& default_instance() {
    return *reinterpret_cast<const GM_RequestSync*>(
        &_GM_RequestSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GM_RequestSync& a, GM_RequestSync& b) { a.Swap(&b); }
  inline void Swap(GM_RequestSync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GM_RequestSync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GM_RequestSync* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GM_RequestSync>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GM_RequestSync& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GM_RequestSync& from) { GM_RequestSync::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GM_RequestSync* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GM_RequestSync"; }

 protected:
  explicit GM_RequestSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GM_RequestSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GM_RequestSync& from);
  GM_RequestSync(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GM_RequestSync&& from) noexcept
      : GM_RequestSync(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSequenceNumberFieldNumber = 1,
  };
  // int32 sequenceNumber = 1;
  bool has_sequencenumber() const;
  void clear_sequencenumber() ;
  ::int32_t sequencenumber() const;
  void set_sequencenumber(::int32_t value);

  private:
  ::int32_t _internal_sequencenumber() const;
  void _internal_set_sequencenumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GM_RequestSync)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GM_RequestSync& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t sequencenumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GM_RequestSync_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GM_RequestSync

// int32 sequenceNumber = 1;
inline bool GM_RequestSync::has_sequencenumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void GM_RequestSync::clear_sequencenumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t GM_RequestSync::sequencenumber() const {
  // @@protoc_insertion_point(field_get:GM_RequestSync.sequenceNumber)
  return _internal_sequencenumber();
}
inline void GM_RequestSync::set_sequencenumber(::int32_t value) {
  _internal_set_sequencenumber(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:GM_RequestSync.sequenceNumber)
}
inline ::int32_t GM_RequestSync::_internal_sequencenumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequencenumber_;
}
inline void GM_RequestSync::_internal_set_sequencenumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = value;
}

// -------------------------------------------------------------------

// GM_RequestSyncResult

// int32 sequenceNumber = 1;
inline bool GM_RequestSyncResult::has_sequencenumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void GM_RequestSyncResult::clear_sequencenumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t GM_RequestSyncResult::sequencenumber() const {
  // @@protoc_insertion_point(field_get:GM_RequestSyncResult.sequenceNumber)
  return _internal_sequencenumber();
}
inline void GM_RequestSyncResult::set_sequencenumber(::int32_t value) {
  _internal_set_sequencenumber(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:GM_RequestSyncResult.sequenceNumber)
}
inline ::int32_t GM_RequestSyncResult::_internal_sequencenumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequencenumber_;
}
inline void GM_RequestSyncResult::_internal_set_sequencenumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequencenumber_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GM_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GM_Type>() {
  return ::GM_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // game_5fmessage_2eproto_2epb_2eh
