// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: login_message.proto
// Protobuf C++ Version: 6.31.0

#include "login_message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr LM_RequestLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR LM_RequestLogin::LM_RequestLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LM_RequestLogin_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LM_RequestLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LM_RequestLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LM_RequestLoginDefaultTypeInternal() {}
  union {
    LM_RequestLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LM_RequestLoginDefaultTypeInternal _LM_RequestLogin_default_instance_;

inline constexpr LM_LoginResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR LM_LoginResult::LM_LoginResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LM_LoginResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LM_LoginResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LM_LoginResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LM_LoginResultDefaultTypeInternal() {}
  union {
    LM_LoginResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LM_LoginResultDefaultTypeInternal _LM_LoginResult_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_login_5fmessage_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_login_5fmessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_login_5fmessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::LM_RequestLogin, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::LM_RequestLogin, _impl_.nickname_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::LM_LoginResult, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::LM_LoginResult, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::LM_LoginResult, _impl_.reason_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::LM_RequestLogin)},
        {5, sizeof(::LM_LoginResult)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_LM_RequestLogin_default_instance_._instance,
    &::_LM_LoginResult_default_instance_._instance,
};
const char descriptor_table_protodef_login_5fmessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023login_message.proto\"#\n\017LM_RequestLogin"
    "\022\020\n\010nickname\030\001 \001(\t\"/\n\016LM_LoginResult\022\r\n\005"
    "token\030\001 \001(\004\022\016\n\006reason\030\002 \001(\t*_\n\007LM_Type\022\022"
    "\n\016LM_UNSPECIFIED\020\000\022\023\n\017LM_DISCONNECTED\020d\022"
    "\024\n\020CM_REQUEST_LOGIN\020e\022\025\n\021SM_RESPONSE_LOG"
    "IN\020fb\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_login_5fmessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_login_5fmessage_2eproto = {
    false,
    false,
    217,
    descriptor_table_protodef_login_5fmessage_2eproto,
    "login_message.proto",
    &descriptor_table_login_5fmessage_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_login_5fmessage_2eproto::offsets,
    file_level_enum_descriptors_login_5fmessage_2eproto,
    file_level_service_descriptors_login_5fmessage_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL LM_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_login_5fmessage_2eproto);
  return file_level_enum_descriptors_login_5fmessage_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t LM_Type_internal_data_[] = {
    65536u, 196608u, 101u, 100u, 102u, };
// ===================================================================

class LM_RequestLogin::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<LM_RequestLogin>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LM_RequestLogin, _impl_._has_bits_);
};

LM_RequestLogin::LM_RequestLogin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LM_RequestLogin_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LM_RequestLogin)
}
PROTOBUF_NDEBUG_INLINE LM_RequestLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::LM_RequestLogin& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nickname_(arena, from.nickname_) {}

LM_RequestLogin::LM_RequestLogin(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const LM_RequestLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LM_RequestLogin_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LM_RequestLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:LM_RequestLogin)
}
PROTOBUF_NDEBUG_INLINE LM_RequestLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nickname_(arena) {}

inline void LM_RequestLogin::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LM_RequestLogin::~LM_RequestLogin() {
  // @@protoc_insertion_point(destructor:LM_RequestLogin)
  SharedDtor(*this);
}
inline void LM_RequestLogin::SharedDtor(MessageLite& self) {
  LM_RequestLogin& this_ = static_cast<LM_RequestLogin&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nickname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LM_RequestLogin::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LM_RequestLogin(arena);
}
constexpr auto LM_RequestLogin::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LM_RequestLogin),
                                            alignof(LM_RequestLogin));
}
constexpr auto LM_RequestLogin::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LM_RequestLogin_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LM_RequestLogin::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LM_RequestLogin>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LM_RequestLogin::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LM_RequestLogin>(), &LM_RequestLogin::ByteSizeLong,
              &LM_RequestLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LM_RequestLogin, _impl_._cached_size_),
          false,
      },
      &LM_RequestLogin::kDescriptorMethods,
      &descriptor_table_login_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LM_RequestLogin_class_data_ =
        LM_RequestLogin::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LM_RequestLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LM_RequestLogin_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LM_RequestLogin_class_data_.tc_table);
  return LM_RequestLogin_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2>
LM_RequestLogin::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LM_RequestLogin, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LM_RequestLogin_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LM_RequestLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nickname = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(LM_RequestLogin, _impl_.nickname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nickname = 1;
    {PROTOBUF_FIELD_OFFSET(LM_RequestLogin, _impl_.nickname_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\10\0\0\0\0\0\0"
    "LM_RequestLogin"
    "nickname"
  }},
};
PROTOBUF_NOINLINE void LM_RequestLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:LM_RequestLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.nickname_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LM_RequestLogin::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LM_RequestLogin& this_ = static_cast<const LM_RequestLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LM_RequestLogin::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LM_RequestLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:LM_RequestLogin)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string nickname = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_nickname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LM_RequestLogin.nickname");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LM_RequestLogin)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LM_RequestLogin::ByteSizeLong(const MessageLite& base) {
  const LM_RequestLogin& this_ = static_cast<const LM_RequestLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LM_RequestLogin::ByteSizeLong() const {
  const LM_RequestLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:LM_RequestLogin)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string nickname = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_nickname());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LM_RequestLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LM_RequestLogin*>(&to_msg);
  auto& from = static_cast<const LM_RequestLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LM_RequestLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LM_RequestLogin::CopyFrom(const LM_RequestLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LM_RequestLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LM_RequestLogin::InternalSwap(LM_RequestLogin* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
}

::google::protobuf::Metadata LM_RequestLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LM_LoginResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<LM_LoginResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_._has_bits_);
};

LM_LoginResult::LM_LoginResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LM_LoginResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LM_LoginResult)
}
PROTOBUF_NDEBUG_INLINE LM_LoginResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::LM_LoginResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

LM_LoginResult::LM_LoginResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const LM_LoginResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LM_LoginResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LM_LoginResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.token_ = from._impl_.token_;

  // @@protoc_insertion_point(copy_constructor:LM_LoginResult)
}
PROTOBUF_NDEBUG_INLINE LM_LoginResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void LM_LoginResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.token_ = {};
}
LM_LoginResult::~LM_LoginResult() {
  // @@protoc_insertion_point(destructor:LM_LoginResult)
  SharedDtor(*this);
}
inline void LM_LoginResult::SharedDtor(MessageLite& self) {
  LM_LoginResult& this_ = static_cast<LM_LoginResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LM_LoginResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LM_LoginResult(arena);
}
constexpr auto LM_LoginResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LM_LoginResult),
                                            alignof(LM_LoginResult));
}
constexpr auto LM_LoginResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LM_LoginResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LM_LoginResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LM_LoginResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LM_LoginResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LM_LoginResult>(), &LM_LoginResult::ByteSizeLong,
              &LM_LoginResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_._cached_size_),
          false,
      },
      &LM_LoginResult::kDescriptorMethods,
      &descriptor_table_login_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LM_LoginResult_class_data_ =
        LM_LoginResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LM_LoginResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LM_LoginResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LM_LoginResult_class_data_.tc_table);
  return LM_LoginResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2>
LM_LoginResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LM_LoginResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LM_LoginResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string reason = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_.reason_)}},
    // uint64 token = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LM_LoginResult, _impl_.token_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 token = 1;
    {PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_.token_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string reason = 2;
    {PROTOBUF_FIELD_OFFSET(LM_LoginResult, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\6\0\0\0\0\0"
    "LM_LoginResult"
    "reason"
  }},
};
PROTOBUF_NOINLINE void LM_LoginResult::Clear() {
// @@protoc_insertion_point(message_clear_start:LM_LoginResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.reason_.ClearNonDefaultToEmpty();
  }
  _impl_.token_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LM_LoginResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LM_LoginResult& this_ = static_cast<const LM_LoginResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LM_LoginResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LM_LoginResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:LM_LoginResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 token = 1;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_token(), target);
  }

  // string reason = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_reason();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LM_LoginResult.reason");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LM_LoginResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LM_LoginResult::ByteSizeLong(const MessageLite& base) {
  const LM_LoginResult& this_ = static_cast<const LM_LoginResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LM_LoginResult::ByteSizeLong() const {
  const LM_LoginResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:LM_LoginResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string reason = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_reason());
    }
    // uint64 token = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_token());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LM_LoginResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LM_LoginResult*>(&to_msg);
  auto& from = static_cast<const LM_LoginResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LM_LoginResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_reason(from._internal_reason());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.token_ = from._impl_.token_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LM_LoginResult::CopyFrom(const LM_LoginResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LM_LoginResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LM_LoginResult::InternalSwap(LM_LoginResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
  swap(_impl_.token_, other->_impl_.token_);
}

::google::protobuf::Metadata LM_LoginResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_login_5fmessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
