// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto_message.proto
// Protobuf C++ Version: 6.31.0

#ifndef proto_5fmessage_2eproto_2epb_2eh
#define proto_5fmessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_5fmessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_5fmessage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_5fmessage_2eproto;
}  // extern "C"
enum PROTO_MessageType : int;
extern const uint32_t PROTO_MessageType_internal_data_[];
class PROTO_LoginResult;
struct PROTO_LoginResultDefaultTypeInternal;
extern PROTO_LoginResultDefaultTypeInternal _PROTO_LoginResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_LoginResult_class_data_;
class PROTO_ObjectTransform;
struct PROTO_ObjectTransformDefaultTypeInternal;
extern PROTO_ObjectTransformDefaultTypeInternal _PROTO_ObjectTransform_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_ObjectTransform_class_data_;
class PROTO_ReportCharacterPhysics;
struct PROTO_ReportCharacterPhysicsDefaultTypeInternal;
extern PROTO_ReportCharacterPhysicsDefaultTypeInternal _PROTO_ReportCharacterPhysics_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_ReportCharacterPhysics_class_data_;
class PROTO_RequestLogin;
struct PROTO_RequestLoginDefaultTypeInternal;
extern PROTO_RequestLoginDefaultTypeInternal _PROTO_RequestLogin_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_RequestLogin_class_data_;
class PROTO_RequestSync;
struct PROTO_RequestSyncDefaultTypeInternal;
extern PROTO_RequestSyncDefaultTypeInternal _PROTO_RequestSync_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_RequestSync_class_data_;
class PROTO_RequestSyncResult;
struct PROTO_RequestSyncResultDefaultTypeInternal;
extern PROTO_RequestSyncResultDefaultTypeInternal _PROTO_RequestSyncResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_RequestSyncResult_class_data_;
class PROTO_SyncCharacterPhysics;
struct PROTO_SyncCharacterPhysicsDefaultTypeInternal;
extern PROTO_SyncCharacterPhysicsDefaultTypeInternal _PROTO_SyncCharacterPhysics_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PROTO_SyncCharacterPhysics_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::PROTO_MessageType_internal_data_>
    internal::EnumTraitsImpl::value<::PROTO_MessageType>;
}  // namespace protobuf
}  // namespace google

enum PROTO_MessageType : int {
  UNSPECIFIED = 0,
  REQUEST_LOGIN = 1,
  LOGIN_RESULT = 2,
  REQUEST_SYNC = 3,
  REQUEST_SYNC_RESULT = 4,
  REPORT_CHARACTER_PHYSICS = 5,
  SYNC_CHARACTER_PHYSICS = 6,
  PROTO_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PROTO_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PROTO_MessageType_internal_data_[];
inline constexpr PROTO_MessageType PROTO_MessageType_MIN =
    static_cast<PROTO_MessageType>(0);
inline constexpr PROTO_MessageType PROTO_MessageType_MAX =
    static_cast<PROTO_MessageType>(6);
inline bool PROTO_MessageType_IsValid(int value) {
  return 0 <= value && value <= 6;
}
inline constexpr int PROTO_MessageType_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PROTO_MessageType_descriptor();
template <typename T>
const ::std::string& PROTO_MessageType_Name(T value) {
  static_assert(::std::is_same<T, PROTO_MessageType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PROTO_MessageType_Name().");
  return PROTO_MessageType_Name(static_cast<PROTO_MessageType>(value));
}
template <>
inline const ::std::string& PROTO_MessageType_Name(PROTO_MessageType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PROTO_MessageType_descriptor, 0, 6>(
      static_cast<int>(value));
}
inline bool PROTO_MessageType_Parse(
    ::absl::string_view name, PROTO_MessageType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PROTO_MessageType>(PROTO_MessageType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PROTO_RequestSyncResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_RequestSyncResult) */ {
 public:
  inline PROTO_RequestSyncResult() : PROTO_RequestSyncResult(nullptr) {}
  ~PROTO_RequestSyncResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_RequestSyncResult* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_RequestSyncResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_RequestSyncResult(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_RequestSyncResult(const PROTO_RequestSyncResult& from) : PROTO_RequestSyncResult(nullptr, from) {}
  inline PROTO_RequestSyncResult(PROTO_RequestSyncResult&& from) noexcept
      : PROTO_RequestSyncResult(nullptr, ::std::move(from)) {}
  inline PROTO_RequestSyncResult& operator=(const PROTO_RequestSyncResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_RequestSyncResult& operator=(PROTO_RequestSyncResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_RequestSyncResult& default_instance() {
    return *reinterpret_cast<const PROTO_RequestSyncResult*>(
        &_PROTO_RequestSyncResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PROTO_RequestSyncResult& a, PROTO_RequestSyncResult& b) { a.Swap(&b); }
  inline void Swap(PROTO_RequestSyncResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_RequestSyncResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_RequestSyncResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_RequestSyncResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_RequestSyncResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_RequestSyncResult& from) { PROTO_RequestSyncResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_RequestSyncResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_RequestSyncResult"; }

 protected:
  explicit PROTO_RequestSyncResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_RequestSyncResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_RequestSyncResult& from);
  PROTO_RequestSyncResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_RequestSyncResult&& from) noexcept
      : PROTO_RequestSyncResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRoomIndexFieldNumber = 1,
  };
  // int32 roomIndex = 1;
  bool has_roomindex() const;
  void clear_roomindex() ;
  ::int32_t roomindex() const;
  void set_roomindex(::int32_t value);

  private:
  ::int32_t _internal_roomindex() const;
  void _internal_set_roomindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PROTO_RequestSyncResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_RequestSyncResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t roomindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_RequestSyncResult_class_data_;
// -------------------------------------------------------------------

class PROTO_RequestSync final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_RequestSync) */ {
 public:
  inline PROTO_RequestSync() : PROTO_RequestSync(nullptr) {}
  ~PROTO_RequestSync() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_RequestSync* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_RequestSync));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_RequestSync(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_RequestSync(const PROTO_RequestSync& from) : PROTO_RequestSync(nullptr, from) {}
  inline PROTO_RequestSync(PROTO_RequestSync&& from) noexcept
      : PROTO_RequestSync(nullptr, ::std::move(from)) {}
  inline PROTO_RequestSync& operator=(const PROTO_RequestSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_RequestSync& operator=(PROTO_RequestSync&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_RequestSync& default_instance() {
    return *reinterpret_cast<const PROTO_RequestSync*>(
        &_PROTO_RequestSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PROTO_RequestSync& a, PROTO_RequestSync& b) { a.Swap(&b); }
  inline void Swap(PROTO_RequestSync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_RequestSync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_RequestSync* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_RequestSync>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_RequestSync& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_RequestSync& from) { PROTO_RequestSync::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_RequestSync* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_RequestSync"; }

 protected:
  explicit PROTO_RequestSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_RequestSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_RequestSync& from);
  PROTO_RequestSync(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_RequestSync&& from) noexcept
      : PROTO_RequestSync(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientIndexFieldNumber = 1,
  };
  // int32 clientIndex = 1;
  bool has_clientindex() const;
  void clear_clientindex() ;
  ::int32_t clientindex() const;
  void set_clientindex(::int32_t value);

  private:
  ::int32_t _internal_clientindex() const;
  void _internal_set_clientindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PROTO_RequestSync)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_RequestSync& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t clientindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_RequestSync_class_data_;
// -------------------------------------------------------------------

class PROTO_RequestLogin final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_RequestLogin) */ {
 public:
  inline PROTO_RequestLogin() : PROTO_RequestLogin(nullptr) {}
  ~PROTO_RequestLogin() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_RequestLogin* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_RequestLogin));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_RequestLogin(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_RequestLogin(const PROTO_RequestLogin& from) : PROTO_RequestLogin(nullptr, from) {}
  inline PROTO_RequestLogin(PROTO_RequestLogin&& from) noexcept
      : PROTO_RequestLogin(nullptr, ::std::move(from)) {}
  inline PROTO_RequestLogin& operator=(const PROTO_RequestLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_RequestLogin& operator=(PROTO_RequestLogin&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_RequestLogin& default_instance() {
    return *reinterpret_cast<const PROTO_RequestLogin*>(
        &_PROTO_RequestLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PROTO_RequestLogin& a, PROTO_RequestLogin& b) { a.Swap(&b); }
  inline void Swap(PROTO_RequestLogin* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_RequestLogin* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_RequestLogin* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_RequestLogin>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_RequestLogin& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_RequestLogin& from) { PROTO_RequestLogin::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_RequestLogin* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_RequestLogin"; }

 protected:
  explicit PROTO_RequestLogin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_RequestLogin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_RequestLogin& from);
  PROTO_RequestLogin(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_RequestLogin&& from) noexcept
      : PROTO_RequestLogin(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNicknameFieldNumber = 1,
  };
  // string nickname = 1;
  bool has_nickname() const;
  void clear_nickname() ;
  const ::std::string& nickname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nickname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nickname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nickname();
  void set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nickname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nickname();

  public:
  // @@protoc_insertion_point(class_scope:PROTO_RequestLogin)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 35,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_RequestLogin& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nickname_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_RequestLogin_class_data_;
// -------------------------------------------------------------------

class PROTO_ObjectTransform final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_ObjectTransform) */ {
 public:
  inline PROTO_ObjectTransform() : PROTO_ObjectTransform(nullptr) {}
  ~PROTO_ObjectTransform() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_ObjectTransform* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_ObjectTransform));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_ObjectTransform(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_ObjectTransform(const PROTO_ObjectTransform& from) : PROTO_ObjectTransform(nullptr, from) {}
  inline PROTO_ObjectTransform(PROTO_ObjectTransform&& from) noexcept
      : PROTO_ObjectTransform(nullptr, ::std::move(from)) {}
  inline PROTO_ObjectTransform& operator=(const PROTO_ObjectTransform& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_ObjectTransform& operator=(PROTO_ObjectTransform&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_ObjectTransform& default_instance() {
    return *reinterpret_cast<const PROTO_ObjectTransform*>(
        &_PROTO_ObjectTransform_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PROTO_ObjectTransform& a, PROTO_ObjectTransform& b) { a.Swap(&b); }
  inline void Swap(PROTO_ObjectTransform* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_ObjectTransform* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_ObjectTransform* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_ObjectTransform>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_ObjectTransform& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_ObjectTransform& from) { PROTO_ObjectTransform::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_ObjectTransform* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_ObjectTransform"; }

 protected:
  explicit PROTO_ObjectTransform(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_ObjectTransform(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_ObjectTransform& from);
  PROTO_ObjectTransform(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_ObjectTransform&& from) noexcept
      : PROTO_ObjectTransform(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientIndexFieldNumber = 1,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kZFieldNumber = 5,
    kRFieldNumber = 6,
  };
  // int32 clientIndex = 1;
  bool has_clientindex() const;
  void clear_clientindex() ;
  ::int32_t clientindex() const;
  void set_clientindex(::int32_t value);

  private:
  ::int32_t _internal_clientindex() const;
  void _internal_set_clientindex(::int32_t value);

  public:
  // float x = 3;
  bool has_x() const;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 4;
  bool has_y() const;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 5;
  bool has_z() const;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // float r = 6;
  bool has_r() const;
  void clear_r() ;
  float r() const;
  void set_r(float value);

  private:
  float _internal_r() const;
  void _internal_set_r(float value);

  public:
  // @@protoc_insertion_point(class_scope:PROTO_ObjectTransform)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_ObjectTransform& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t clientindex_;
    float x_;
    float y_;
    float z_;
    float r_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_ObjectTransform_class_data_;
// -------------------------------------------------------------------

class PROTO_LoginResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_LoginResult) */ {
 public:
  inline PROTO_LoginResult() : PROTO_LoginResult(nullptr) {}
  ~PROTO_LoginResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_LoginResult* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_LoginResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_LoginResult(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_LoginResult(const PROTO_LoginResult& from) : PROTO_LoginResult(nullptr, from) {}
  inline PROTO_LoginResult(PROTO_LoginResult&& from) noexcept
      : PROTO_LoginResult(nullptr, ::std::move(from)) {}
  inline PROTO_LoginResult& operator=(const PROTO_LoginResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_LoginResult& operator=(PROTO_LoginResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_LoginResult& default_instance() {
    return *reinterpret_cast<const PROTO_LoginResult*>(
        &_PROTO_LoginResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PROTO_LoginResult& a, PROTO_LoginResult& b) { a.Swap(&b); }
  inline void Swap(PROTO_LoginResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_LoginResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_LoginResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_LoginResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_LoginResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_LoginResult& from) { PROTO_LoginResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_LoginResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_LoginResult"; }

 protected:
  explicit PROTO_LoginResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_LoginResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_LoginResult& from);
  PROTO_LoginResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_LoginResult&& from) noexcept
      : PROTO_LoginResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReasonFieldNumber = 2,
    kClientIndexFieldNumber = 1,
  };
  // string reason = 2;
  bool has_reason() const;
  void clear_reason() ;
  const ::std::string& reason() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_reason(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_reason();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_reason();
  void set_allocated_reason(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_reason() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_reason();

  public:
  // int32 clientIndex = 1;
  bool has_clientindex() const;
  void clear_clientindex() ;
  ::int32_t clientindex() const;
  void set_clientindex(::int32_t value);

  private:
  ::int32_t _internal_clientindex() const;
  void _internal_set_clientindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PROTO_LoginResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 32,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_LoginResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr reason_;
    ::int32_t clientindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_LoginResult_class_data_;
// -------------------------------------------------------------------

class PROTO_SyncCharacterPhysics final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_SyncCharacterPhysics) */ {
 public:
  inline PROTO_SyncCharacterPhysics() : PROTO_SyncCharacterPhysics(nullptr) {}
  ~PROTO_SyncCharacterPhysics() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_SyncCharacterPhysics* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_SyncCharacterPhysics));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_SyncCharacterPhysics(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_SyncCharacterPhysics(const PROTO_SyncCharacterPhysics& from) : PROTO_SyncCharacterPhysics(nullptr, from) {}
  inline PROTO_SyncCharacterPhysics(PROTO_SyncCharacterPhysics&& from) noexcept
      : PROTO_SyncCharacterPhysics(nullptr, ::std::move(from)) {}
  inline PROTO_SyncCharacterPhysics& operator=(const PROTO_SyncCharacterPhysics& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_SyncCharacterPhysics& operator=(PROTO_SyncCharacterPhysics&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_SyncCharacterPhysics& default_instance() {
    return *reinterpret_cast<const PROTO_SyncCharacterPhysics*>(
        &_PROTO_SyncCharacterPhysics_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(PROTO_SyncCharacterPhysics& a, PROTO_SyncCharacterPhysics& b) { a.Swap(&b); }
  inline void Swap(PROTO_SyncCharacterPhysics* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_SyncCharacterPhysics* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_SyncCharacterPhysics* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_SyncCharacterPhysics>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_SyncCharacterPhysics& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_SyncCharacterPhysics& from) { PROTO_SyncCharacterPhysics::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_SyncCharacterPhysics* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_SyncCharacterPhysics"; }

 protected:
  explicit PROTO_SyncCharacterPhysics(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_SyncCharacterPhysics(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_SyncCharacterPhysics& from);
  PROTO_SyncCharacterPhysics(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_SyncCharacterPhysics&& from) noexcept
      : PROTO_SyncCharacterPhysics(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTransfomsFieldNumber = 1,
  };
  // repeated .PROTO_ObjectTransform transfoms = 1;
  int transfoms_size() const;
  private:
  int _internal_transfoms_size() const;

  public:
  void clear_transfoms() ;
  ::PROTO_ObjectTransform* PROTOBUF_NONNULL mutable_transfoms(int index);
  ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>* PROTOBUF_NONNULL mutable_transfoms();

  private:
  const ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>& _internal_transfoms() const;
  ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>* PROTOBUF_NONNULL _internal_mutable_transfoms();
  public:
  const ::PROTO_ObjectTransform& transfoms(int index) const;
  ::PROTO_ObjectTransform* PROTOBUF_NONNULL add_transfoms();
  const ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>& transfoms() const;
  // @@protoc_insertion_point(class_scope:PROTO_SyncCharacterPhysics)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_SyncCharacterPhysics& from_msg);
    ::google::protobuf::RepeatedPtrField< ::PROTO_ObjectTransform > transfoms_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_SyncCharacterPhysics_class_data_;
// -------------------------------------------------------------------

class PROTO_ReportCharacterPhysics final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PROTO_ReportCharacterPhysics) */ {
 public:
  inline PROTO_ReportCharacterPhysics() : PROTO_ReportCharacterPhysics(nullptr) {}
  ~PROTO_ReportCharacterPhysics() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PROTO_ReportCharacterPhysics* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PROTO_ReportCharacterPhysics));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PROTO_ReportCharacterPhysics(::google::protobuf::internal::ConstantInitialized);

  inline PROTO_ReportCharacterPhysics(const PROTO_ReportCharacterPhysics& from) : PROTO_ReportCharacterPhysics(nullptr, from) {}
  inline PROTO_ReportCharacterPhysics(PROTO_ReportCharacterPhysics&& from) noexcept
      : PROTO_ReportCharacterPhysics(nullptr, ::std::move(from)) {}
  inline PROTO_ReportCharacterPhysics& operator=(const PROTO_ReportCharacterPhysics& from) {
    CopyFrom(from);
    return *this;
  }
  inline PROTO_ReportCharacterPhysics& operator=(PROTO_ReportCharacterPhysics&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PROTO_ReportCharacterPhysics& default_instance() {
    return *reinterpret_cast<const PROTO_ReportCharacterPhysics*>(
        &_PROTO_ReportCharacterPhysics_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(PROTO_ReportCharacterPhysics& a, PROTO_ReportCharacterPhysics& b) { a.Swap(&b); }
  inline void Swap(PROTO_ReportCharacterPhysics* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PROTO_ReportCharacterPhysics* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PROTO_ReportCharacterPhysics* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PROTO_ReportCharacterPhysics>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PROTO_ReportCharacterPhysics& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PROTO_ReportCharacterPhysics& from) { PROTO_ReportCharacterPhysics::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PROTO_ReportCharacterPhysics* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PROTO_ReportCharacterPhysics"; }

 protected:
  explicit PROTO_ReportCharacterPhysics(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PROTO_ReportCharacterPhysics(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_ReportCharacterPhysics& from);
  PROTO_ReportCharacterPhysics(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PROTO_ReportCharacterPhysics&& from) noexcept
      : PROTO_ReportCharacterPhysics(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTransformFieldNumber = 2,
    kRoomIndexFieldNumber = 1,
  };
  // .PROTO_ObjectTransform transform = 2;
  bool has_transform() const;
  void clear_transform() ;
  const ::PROTO_ObjectTransform& transform() const;
  [[nodiscard]] ::PROTO_ObjectTransform* PROTOBUF_NULLABLE release_transform();
  ::PROTO_ObjectTransform* PROTOBUF_NONNULL mutable_transform();
  void set_allocated_transform(::PROTO_ObjectTransform* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_transform(::PROTO_ObjectTransform* PROTOBUF_NULLABLE value);
  ::PROTO_ObjectTransform* PROTOBUF_NULLABLE unsafe_arena_release_transform();

  private:
  const ::PROTO_ObjectTransform& _internal_transform() const;
  ::PROTO_ObjectTransform* PROTOBUF_NONNULL _internal_mutable_transform();

  public:
  // int32 roomIndex = 1;
  bool has_roomindex() const;
  void clear_roomindex() ;
  ::int32_t roomindex() const;
  void set_roomindex(::int32_t value);

  private:
  ::int32_t _internal_roomindex() const;
  void _internal_set_roomindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PROTO_ReportCharacterPhysics)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PROTO_ReportCharacterPhysics& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::PROTO_ObjectTransform* PROTOBUF_NULLABLE transform_;
    ::int32_t roomindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PROTO_ReportCharacterPhysics_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PROTO_ObjectTransform

// int32 clientIndex = 1;
inline bool PROTO_ObjectTransform::has_clientindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PROTO_ObjectTransform::clear_clientindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PROTO_ObjectTransform::clientindex() const {
  // @@protoc_insertion_point(field_get:PROTO_ObjectTransform.clientIndex)
  return _internal_clientindex();
}
inline void PROTO_ObjectTransform::set_clientindex(::int32_t value) {
  _internal_set_clientindex(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PROTO_ObjectTransform.clientIndex)
}
inline ::int32_t PROTO_ObjectTransform::_internal_clientindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientindex_;
}
inline void PROTO_ObjectTransform::_internal_set_clientindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientindex_ = value;
}

// float x = 3;
inline bool PROTO_ObjectTransform::has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void PROTO_ObjectTransform::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float PROTO_ObjectTransform::x() const {
  // @@protoc_insertion_point(field_get:PROTO_ObjectTransform.x)
  return _internal_x();
}
inline void PROTO_ObjectTransform::set_x(float value) {
  _internal_set_x(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:PROTO_ObjectTransform.x)
}
inline float PROTO_ObjectTransform::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void PROTO_ObjectTransform::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 4;
inline bool PROTO_ObjectTransform::has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void PROTO_ObjectTransform::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float PROTO_ObjectTransform::y() const {
  // @@protoc_insertion_point(field_get:PROTO_ObjectTransform.y)
  return _internal_y();
}
inline void PROTO_ObjectTransform::set_y(float value) {
  _internal_set_y(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:PROTO_ObjectTransform.y)
}
inline float PROTO_ObjectTransform::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void PROTO_ObjectTransform::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 5;
inline bool PROTO_ObjectTransform::has_z() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void PROTO_ObjectTransform::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float PROTO_ObjectTransform::z() const {
  // @@protoc_insertion_point(field_get:PROTO_ObjectTransform.z)
  return _internal_z();
}
inline void PROTO_ObjectTransform::set_z(float value) {
  _internal_set_z(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:PROTO_ObjectTransform.z)
}
inline float PROTO_ObjectTransform::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void PROTO_ObjectTransform::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// float r = 6;
inline bool PROTO_ObjectTransform::has_r() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void PROTO_ObjectTransform::clear_r() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.r_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline float PROTO_ObjectTransform::r() const {
  // @@protoc_insertion_point(field_get:PROTO_ObjectTransform.r)
  return _internal_r();
}
inline void PROTO_ObjectTransform::set_r(float value) {
  _internal_set_r(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:PROTO_ObjectTransform.r)
}
inline float PROTO_ObjectTransform::_internal_r() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.r_;
}
inline void PROTO_ObjectTransform::_internal_set_r(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.r_ = value;
}

// -------------------------------------------------------------------

// PROTO_RequestLogin

// string nickname = 1;
inline bool PROTO_RequestLogin::has_nickname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PROTO_RequestLogin::clear_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nickname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PROTO_RequestLogin::nickname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PROTO_RequestLogin.nickname)
  return _internal_nickname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PROTO_RequestLogin::set_nickname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nickname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PROTO_RequestLogin.nickname)
}
inline ::std::string* PROTOBUF_NONNULL PROTO_RequestLogin::mutable_nickname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:PROTO_RequestLogin.nickname)
  return _s;
}
inline const ::std::string& PROTO_RequestLogin::_internal_nickname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nickname_.Get();
}
inline void PROTO_RequestLogin::_internal_set_nickname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nickname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PROTO_RequestLogin::_internal_mutable_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.nickname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PROTO_RequestLogin::release_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PROTO_RequestLogin.nickname)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.nickname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nickname_.Set("", GetArena());
  }
  return released;
}
inline void PROTO_RequestLogin::set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.nickname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PROTO_RequestLogin.nickname)
}

// -------------------------------------------------------------------

// PROTO_LoginResult

// int32 clientIndex = 1;
inline bool PROTO_LoginResult::has_clientindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void PROTO_LoginResult::clear_clientindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t PROTO_LoginResult::clientindex() const {
  // @@protoc_insertion_point(field_get:PROTO_LoginResult.clientIndex)
  return _internal_clientindex();
}
inline void PROTO_LoginResult::set_clientindex(::int32_t value) {
  _internal_set_clientindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:PROTO_LoginResult.clientIndex)
}
inline ::int32_t PROTO_LoginResult::_internal_clientindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientindex_;
}
inline void PROTO_LoginResult::_internal_set_clientindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientindex_ = value;
}

// string reason = 2;
inline bool PROTO_LoginResult::has_reason() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PROTO_LoginResult::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PROTO_LoginResult::reason() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PROTO_LoginResult.reason)
  return _internal_reason();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PROTO_LoginResult::set_reason(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reason_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PROTO_LoginResult.reason)
}
inline ::std::string* PROTOBUF_NONNULL PROTO_LoginResult::mutable_reason()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:PROTO_LoginResult.reason)
  return _s;
}
inline const ::std::string& PROTO_LoginResult::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reason_.Get();
}
inline void PROTO_LoginResult::_internal_set_reason(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reason_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PROTO_LoginResult::_internal_mutable_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.reason_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PROTO_LoginResult::release_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PROTO_LoginResult.reason)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.reason_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.reason_.Set("", GetArena());
  }
  return released;
}
inline void PROTO_LoginResult::set_allocated_reason(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reason_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PROTO_LoginResult.reason)
}

// -------------------------------------------------------------------

// PROTO_RequestSync

// int32 clientIndex = 1;
inline bool PROTO_RequestSync::has_clientindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PROTO_RequestSync::clear_clientindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PROTO_RequestSync::clientindex() const {
  // @@protoc_insertion_point(field_get:PROTO_RequestSync.clientIndex)
  return _internal_clientindex();
}
inline void PROTO_RequestSync::set_clientindex(::int32_t value) {
  _internal_set_clientindex(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PROTO_RequestSync.clientIndex)
}
inline ::int32_t PROTO_RequestSync::_internal_clientindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientindex_;
}
inline void PROTO_RequestSync::_internal_set_clientindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientindex_ = value;
}

// -------------------------------------------------------------------

// PROTO_RequestSyncResult

// int32 roomIndex = 1;
inline bool PROTO_RequestSyncResult::has_roomindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PROTO_RequestSyncResult::clear_roomindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PROTO_RequestSyncResult::roomindex() const {
  // @@protoc_insertion_point(field_get:PROTO_RequestSyncResult.roomIndex)
  return _internal_roomindex();
}
inline void PROTO_RequestSyncResult::set_roomindex(::int32_t value) {
  _internal_set_roomindex(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PROTO_RequestSyncResult.roomIndex)
}
inline ::int32_t PROTO_RequestSyncResult::_internal_roomindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomindex_;
}
inline void PROTO_RequestSyncResult::_internal_set_roomindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = value;
}

// -------------------------------------------------------------------

// PROTO_ReportCharacterPhysics

// int32 roomIndex = 1;
inline bool PROTO_ReportCharacterPhysics::has_roomindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void PROTO_ReportCharacterPhysics::clear_roomindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t PROTO_ReportCharacterPhysics::roomindex() const {
  // @@protoc_insertion_point(field_get:PROTO_ReportCharacterPhysics.roomIndex)
  return _internal_roomindex();
}
inline void PROTO_ReportCharacterPhysics::set_roomindex(::int32_t value) {
  _internal_set_roomindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:PROTO_ReportCharacterPhysics.roomIndex)
}
inline ::int32_t PROTO_ReportCharacterPhysics::_internal_roomindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomindex_;
}
inline void PROTO_ReportCharacterPhysics::_internal_set_roomindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = value;
}

// .PROTO_ObjectTransform transform = 2;
inline bool PROTO_ReportCharacterPhysics::has_transform() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.transform_ != nullptr);
  return value;
}
inline void PROTO_ReportCharacterPhysics::clear_transform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.transform_ != nullptr) _impl_.transform_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::PROTO_ObjectTransform& PROTO_ReportCharacterPhysics::_internal_transform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::PROTO_ObjectTransform* p = _impl_.transform_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTO_ObjectTransform&>(::_PROTO_ObjectTransform_default_instance_);
}
inline const ::PROTO_ObjectTransform& PROTO_ReportCharacterPhysics::transform() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PROTO_ReportCharacterPhysics.transform)
  return _internal_transform();
}
inline void PROTO_ReportCharacterPhysics::unsafe_arena_set_allocated_transform(
    ::PROTO_ObjectTransform* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.transform_);
  }
  _impl_.transform_ = reinterpret_cast<::PROTO_ObjectTransform*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PROTO_ReportCharacterPhysics.transform)
}
inline ::PROTO_ObjectTransform* PROTOBUF_NULLABLE PROTO_ReportCharacterPhysics::release_transform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTO_ObjectTransform* released = _impl_.transform_;
  _impl_.transform_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::PROTO_ObjectTransform* PROTOBUF_NULLABLE PROTO_ReportCharacterPhysics::unsafe_arena_release_transform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PROTO_ReportCharacterPhysics.transform)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTO_ObjectTransform* temp = _impl_.transform_;
  _impl_.transform_ = nullptr;
  return temp;
}
inline ::PROTO_ObjectTransform* PROTOBUF_NONNULL PROTO_ReportCharacterPhysics::_internal_mutable_transform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.transform_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::PROTO_ObjectTransform>(GetArena());
    _impl_.transform_ = reinterpret_cast<::PROTO_ObjectTransform*>(p);
  }
  return _impl_.transform_;
}
inline ::PROTO_ObjectTransform* PROTOBUF_NONNULL PROTO_ReportCharacterPhysics::mutable_transform()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::PROTO_ObjectTransform* _msg = _internal_mutable_transform();
  // @@protoc_insertion_point(field_mutable:PROTO_ReportCharacterPhysics.transform)
  return _msg;
}
inline void PROTO_ReportCharacterPhysics::set_allocated_transform(::PROTO_ObjectTransform* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.transform_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.transform_ = reinterpret_cast<::PROTO_ObjectTransform*>(value);
  // @@protoc_insertion_point(field_set_allocated:PROTO_ReportCharacterPhysics.transform)
}

// -------------------------------------------------------------------

// PROTO_SyncCharacterPhysics

// repeated .PROTO_ObjectTransform transfoms = 1;
inline int PROTO_SyncCharacterPhysics::_internal_transfoms_size() const {
  return _internal_transfoms().size();
}
inline int PROTO_SyncCharacterPhysics::transfoms_size() const {
  return _internal_transfoms_size();
}
inline void PROTO_SyncCharacterPhysics::clear_transfoms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfoms_.Clear();
}
inline ::PROTO_ObjectTransform* PROTOBUF_NONNULL PROTO_SyncCharacterPhysics::mutable_transfoms(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PROTO_SyncCharacterPhysics.transfoms)
  return _internal_mutable_transfoms()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>* PROTOBUF_NONNULL PROTO_SyncCharacterPhysics::mutable_transfoms()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PROTO_SyncCharacterPhysics.transfoms)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_transfoms();
}
inline const ::PROTO_ObjectTransform& PROTO_SyncCharacterPhysics::transfoms(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PROTO_SyncCharacterPhysics.transfoms)
  return _internal_transfoms().Get(index);
}
inline ::PROTO_ObjectTransform* PROTOBUF_NONNULL PROTO_SyncCharacterPhysics::add_transfoms()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::PROTO_ObjectTransform* _add = _internal_mutable_transfoms()->Add();
  // @@protoc_insertion_point(field_add:PROTO_SyncCharacterPhysics.transfoms)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>& PROTO_SyncCharacterPhysics::transfoms() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PROTO_SyncCharacterPhysics.transfoms)
  return _internal_transfoms();
}
inline const ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>&
PROTO_SyncCharacterPhysics::_internal_transfoms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transfoms_;
}
inline ::google::protobuf::RepeatedPtrField<::PROTO_ObjectTransform>* PROTOBUF_NONNULL
PROTO_SyncCharacterPhysics::_internal_mutable_transfoms() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.transfoms_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::PROTO_MessageType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::PROTO_MessageType>() {
  return ::PROTO_MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_5fmessage_2eproto_2epb_2eh
