// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto_message.proto
// Protobuf C++ Version: 6.31.0

#include "proto_message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PROTO_RequestLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PROTO_RequestLogin::PROTO_RequestLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PROTO_RequestLogin_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PROTO_RequestLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PROTO_RequestLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PROTO_RequestLoginDefaultTypeInternal() {}
  union {
    PROTO_RequestLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTO_RequestLoginDefaultTypeInternal _PROTO_RequestLogin_default_instance_;

inline constexpr PROTO_ObjectTransform::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0},
        x_{0},
        y_{0},
        z_{0},
        r_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PROTO_ObjectTransform::PROTO_ObjectTransform(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PROTO_ObjectTransform_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PROTO_ObjectTransformDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PROTO_ObjectTransformDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PROTO_ObjectTransformDefaultTypeInternal() {}
  union {
    PROTO_ObjectTransform _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTO_ObjectTransformDefaultTypeInternal _PROTO_ObjectTransform_default_instance_;

inline constexpr PROTO_LoginResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PROTO_LoginResult::PROTO_LoginResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PROTO_LoginResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PROTO_LoginResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PROTO_LoginResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PROTO_LoginResultDefaultTypeInternal() {}
  union {
    PROTO_LoginResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTO_LoginResultDefaultTypeInternal _PROTO_LoginResult_default_instance_;

inline constexpr CharacterPosition::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0},
        x_{0},
        y_{0},
        z_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CharacterPosition::CharacterPosition(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CharacterPosition_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CharacterPositionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CharacterPositionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CharacterPositionDefaultTypeInternal() {}
  union {
    CharacterPosition _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CharacterPositionDefaultTypeInternal _CharacterPosition_default_instance_;

inline constexpr PROTO_SyncPhysics::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : characters_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PROTO_SyncPhysics::PROTO_SyncPhysics(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PROTO_SyncPhysics_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PROTO_SyncPhysicsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PROTO_SyncPhysicsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PROTO_SyncPhysicsDefaultTypeInternal() {}
  union {
    PROTO_SyncPhysics _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTO_SyncPhysicsDefaultTypeInternal _PROTO_SyncPhysics_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_5fmessage_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_5fmessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_5fmessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CharacterPosition, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CharacterPosition, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::CharacterPosition, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::CharacterPosition, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::CharacterPosition, _impl_.z_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PROTO_ObjectTransform, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PROTO_ObjectTransform, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::PROTO_ObjectTransform, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::PROTO_ObjectTransform, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::PROTO_ObjectTransform, _impl_.z_),
        PROTOBUF_FIELD_OFFSET(::PROTO_ObjectTransform, _impl_.r_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PROTO_RequestLogin, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PROTO_RequestLogin, _impl_.nickname_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PROTO_LoginResult, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PROTO_LoginResult, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::PROTO_LoginResult, _impl_.reason_),
        1,
        0,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::PROTO_SyncPhysics, _impl_.characters_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CharacterPosition)},
        {11, sizeof(::PROTO_ObjectTransform)},
        {24, sizeof(::PROTO_RequestLogin)},
        {29, sizeof(::PROTO_LoginResult)},
        {36, sizeof(::PROTO_SyncPhysics)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_CharacterPosition_default_instance_._instance,
    &::_PROTO_ObjectTransform_default_instance_._instance,
    &::_PROTO_RequestLogin_default_instance_._instance,
    &::_PROTO_LoginResult_default_instance_._instance,
    &::_PROTO_SyncPhysics_default_instance_._instance,
};
const char descriptor_table_protodef_proto_5fmessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023proto_message.proto\"@\n\021CharacterPositi"
    "on\022\n\n\002id\030\001 \001(\005\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002\022\t\n\001"
    "z\030\004 \001(\002\"O\n\025PROTO_ObjectTransform\022\n\n\002id\030\001"
    " \001(\005\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002\022\t\n\001z\030\004 \001(\002\022\t\n"
    "\001r\030\005 \001(\002\"&\n\022PROTO_RequestLogin\022\020\n\010nickna"
    "me\030\001 \001(\t\"3\n\021PROTO_LoginResult\022\016\n\006result\030"
    "\001 \001(\010\022\016\n\006reason\030\002 \001(\t\";\n\021PROTO_SyncPhysi"
    "cs\022&\n\ncharacters\030\001 \003(\0132\022.CharacterPositi"
    "on*b\n\021PROTO_MessageType\022\017\n\013UNSPECIFIED\020\000"
    "\022\021\n\rREQUEST_LOGIN\020\001\022\020\n\014LOGIN_RESULT\020\002\022\027\n"
    "\023REQUEST_SYNC_OBJECT\020\003b\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_proto_5fmessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_5fmessage_2eproto = {
    false,
    false,
    435,
    descriptor_table_protodef_proto_5fmessage_2eproto,
    "proto_message.proto",
    &descriptor_table_proto_5fmessage_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_proto_5fmessage_2eproto::offsets,
    file_level_enum_descriptors_proto_5fmessage_2eproto,
    file_level_service_descriptors_proto_5fmessage_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PROTO_MessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_5fmessage_2eproto);
  return file_level_enum_descriptors_proto_5fmessage_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PROTO_MessageType_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class CharacterPosition::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CharacterPosition>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_._has_bits_);
};

CharacterPosition::CharacterPosition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CharacterPosition_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CharacterPosition)
}
CharacterPosition::CharacterPosition(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CharacterPosition& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CharacterPosition_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CharacterPosition::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CharacterPosition::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::z_));
}
CharacterPosition::~CharacterPosition() {
  // @@protoc_insertion_point(destructor:CharacterPosition)
  SharedDtor(*this);
}
inline void CharacterPosition::SharedDtor(MessageLite& self) {
  CharacterPosition& this_ = static_cast<CharacterPosition&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CharacterPosition::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CharacterPosition(arena);
}
constexpr auto CharacterPosition::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CharacterPosition),
                                            alignof(CharacterPosition));
}
constexpr auto CharacterPosition::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CharacterPosition_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CharacterPosition::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CharacterPosition>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CharacterPosition::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CharacterPosition>(), &CharacterPosition::ByteSizeLong,
              &CharacterPosition::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_._cached_size_),
          false,
      },
      &CharacterPosition::kDescriptorMethods,
      &descriptor_table_proto_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CharacterPosition_class_data_ =
        CharacterPosition::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CharacterPosition::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CharacterPosition_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CharacterPosition_class_data_.tc_table);
  return CharacterPosition_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
CharacterPosition::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CharacterPosition_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CharacterPosition>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float z = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.z_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CharacterPosition, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.id_)}},
    // float x = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.x_)}},
    // float y = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.y_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float x = 2;
    {PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.x_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float y = 3;
    {PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.y_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float z = 4;
    {PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.z_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CharacterPosition::Clear() {
// @@protoc_insertion_point(message_clear_start:CharacterPosition)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.z_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.z_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CharacterPosition::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CharacterPosition& this_ = static_cast<const CharacterPosition&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CharacterPosition::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CharacterPosition& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:CharacterPosition)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_id(), target);
  }

  // float x = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_x(), target);
  }

  // float y = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_y(), target);
  }

  // float z = 4;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_z(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CharacterPosition)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CharacterPosition::ByteSizeLong(const MessageLite& base) {
  const CharacterPosition& this_ = static_cast<const CharacterPosition&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CharacterPosition::ByteSizeLong() const {
  const CharacterPosition& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CharacterPosition)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000000eu & cached_has_bits) * 5;
   {
    // int32 id = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CharacterPosition::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CharacterPosition*>(&to_msg);
  auto& from = static_cast<const CharacterPosition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CharacterPosition)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_impl_.z_ = from._impl_.z_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CharacterPosition::CopyFrom(const CharacterPosition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CharacterPosition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CharacterPosition::InternalSwap(CharacterPosition* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.z_)
      + sizeof(CharacterPosition::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(CharacterPosition, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata CharacterPosition::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PROTO_ObjectTransform::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PROTO_ObjectTransform>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_._has_bits_);
};

PROTO_ObjectTransform::PROTO_ObjectTransform(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_ObjectTransform_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PROTO_ObjectTransform)
}
PROTO_ObjectTransform::PROTO_ObjectTransform(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PROTO_ObjectTransform& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_ObjectTransform_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PROTO_ObjectTransform::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PROTO_ObjectTransform::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, r_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::r_));
}
PROTO_ObjectTransform::~PROTO_ObjectTransform() {
  // @@protoc_insertion_point(destructor:PROTO_ObjectTransform)
  SharedDtor(*this);
}
inline void PROTO_ObjectTransform::SharedDtor(MessageLite& self) {
  PROTO_ObjectTransform& this_ = static_cast<PROTO_ObjectTransform&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PROTO_ObjectTransform::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PROTO_ObjectTransform(arena);
}
constexpr auto PROTO_ObjectTransform::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PROTO_ObjectTransform),
                                            alignof(PROTO_ObjectTransform));
}
constexpr auto PROTO_ObjectTransform::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PROTO_ObjectTransform_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PROTO_ObjectTransform::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PROTO_ObjectTransform>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PROTO_ObjectTransform::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PROTO_ObjectTransform>(), &PROTO_ObjectTransform::ByteSizeLong,
              &PROTO_ObjectTransform::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_._cached_size_),
          false,
      },
      &PROTO_ObjectTransform::kDescriptorMethods,
      &descriptor_table_proto_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PROTO_ObjectTransform_class_data_ =
        PROTO_ObjectTransform::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PROTO_ObjectTransform::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PROTO_ObjectTransform_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PROTO_ObjectTransform_class_data_.tc_table);
  return PROTO_ObjectTransform_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
PROTO_ObjectTransform::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PROTO_ObjectTransform_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PROTO_ObjectTransform>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PROTO_ObjectTransform, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.id_)}},
    // float x = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.x_)}},
    // float y = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.y_)}},
    // float z = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.z_)}},
    // float r = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 4, 0, PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.r_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float x = 2;
    {PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.x_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float y = 3;
    {PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.y_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float z = 4;
    {PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.z_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float r = 5;
    {PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.r_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PROTO_ObjectTransform::Clear() {
// @@protoc_insertion_point(message_clear_start:PROTO_ObjectTransform)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.r_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.r_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PROTO_ObjectTransform::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PROTO_ObjectTransform& this_ = static_cast<const PROTO_ObjectTransform&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PROTO_ObjectTransform::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PROTO_ObjectTransform& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:PROTO_ObjectTransform)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_id(), target);
  }

  // float x = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_x(), target);
  }

  // float y = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_y(), target);
  }

  // float z = 4;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_z(), target);
  }

  // float r = 5;
  if ((cached_has_bits & 0x00000010u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this_._internal_r(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PROTO_ObjectTransform)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PROTO_ObjectTransform::ByteSizeLong(const MessageLite& base) {
  const PROTO_ObjectTransform& this_ = static_cast<const PROTO_ObjectTransform&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PROTO_ObjectTransform::ByteSizeLong() const {
  const PROTO_ObjectTransform& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PROTO_ObjectTransform)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000001eu & cached_has_bits) * 5;
   {
    // int32 id = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PROTO_ObjectTransform::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PROTO_ObjectTransform*>(&to_msg);
  auto& from = static_cast<const PROTO_ObjectTransform&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PROTO_ObjectTransform)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_impl_.z_ = from._impl_.z_;
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _this->_impl_.r_ = from._impl_.r_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PROTO_ObjectTransform::CopyFrom(const PROTO_ObjectTransform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PROTO_ObjectTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PROTO_ObjectTransform::InternalSwap(PROTO_ObjectTransform* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.r_)
      + sizeof(PROTO_ObjectTransform::_impl_.r_)
      - PROTOBUF_FIELD_OFFSET(PROTO_ObjectTransform, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata PROTO_ObjectTransform::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PROTO_RequestLogin::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PROTO_RequestLogin>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PROTO_RequestLogin, _impl_._has_bits_);
};

PROTO_RequestLogin::PROTO_RequestLogin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_RequestLogin_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PROTO_RequestLogin)
}
PROTOBUF_NDEBUG_INLINE PROTO_RequestLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::PROTO_RequestLogin& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nickname_(arena, from.nickname_) {}

PROTO_RequestLogin::PROTO_RequestLogin(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PROTO_RequestLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_RequestLogin_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PROTO_RequestLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PROTO_RequestLogin)
}
PROTOBUF_NDEBUG_INLINE PROTO_RequestLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nickname_(arena) {}

inline void PROTO_RequestLogin::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PROTO_RequestLogin::~PROTO_RequestLogin() {
  // @@protoc_insertion_point(destructor:PROTO_RequestLogin)
  SharedDtor(*this);
}
inline void PROTO_RequestLogin::SharedDtor(MessageLite& self) {
  PROTO_RequestLogin& this_ = static_cast<PROTO_RequestLogin&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nickname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PROTO_RequestLogin::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PROTO_RequestLogin(arena);
}
constexpr auto PROTO_RequestLogin::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PROTO_RequestLogin),
                                            alignof(PROTO_RequestLogin));
}
constexpr auto PROTO_RequestLogin::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PROTO_RequestLogin_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PROTO_RequestLogin::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PROTO_RequestLogin>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PROTO_RequestLogin::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PROTO_RequestLogin>(), &PROTO_RequestLogin::ByteSizeLong,
              &PROTO_RequestLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PROTO_RequestLogin, _impl_._cached_size_),
          false,
      },
      &PROTO_RequestLogin::kDescriptorMethods,
      &descriptor_table_proto_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PROTO_RequestLogin_class_data_ =
        PROTO_RequestLogin::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PROTO_RequestLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PROTO_RequestLogin_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PROTO_RequestLogin_class_data_.tc_table);
  return PROTO_RequestLogin_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2>
PROTO_RequestLogin::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PROTO_RequestLogin, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PROTO_RequestLogin_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PROTO_RequestLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nickname = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PROTO_RequestLogin, _impl_.nickname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nickname = 1;
    {PROTOBUF_FIELD_OFFSET(PROTO_RequestLogin, _impl_.nickname_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\10\0\0\0\0\0\0"
    "PROTO_RequestLogin"
    "nickname"
  }},
};
PROTOBUF_NOINLINE void PROTO_RequestLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:PROTO_RequestLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.nickname_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PROTO_RequestLogin::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PROTO_RequestLogin& this_ = static_cast<const PROTO_RequestLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PROTO_RequestLogin::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PROTO_RequestLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:PROTO_RequestLogin)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string nickname = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_nickname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PROTO_RequestLogin.nickname");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PROTO_RequestLogin)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PROTO_RequestLogin::ByteSizeLong(const MessageLite& base) {
  const PROTO_RequestLogin& this_ = static_cast<const PROTO_RequestLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PROTO_RequestLogin::ByteSizeLong() const {
  const PROTO_RequestLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PROTO_RequestLogin)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string nickname = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_nickname());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PROTO_RequestLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PROTO_RequestLogin*>(&to_msg);
  auto& from = static_cast<const PROTO_RequestLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PROTO_RequestLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PROTO_RequestLogin::CopyFrom(const PROTO_RequestLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PROTO_RequestLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PROTO_RequestLogin::InternalSwap(PROTO_RequestLogin* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
}

::google::protobuf::Metadata PROTO_RequestLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PROTO_LoginResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PROTO_LoginResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_._has_bits_);
};

PROTO_LoginResult::PROTO_LoginResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_LoginResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PROTO_LoginResult)
}
PROTOBUF_NDEBUG_INLINE PROTO_LoginResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::PROTO_LoginResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

PROTO_LoginResult::PROTO_LoginResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PROTO_LoginResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_LoginResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PROTO_LoginResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:PROTO_LoginResult)
}
PROTOBUF_NDEBUG_INLINE PROTO_LoginResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void PROTO_LoginResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
PROTO_LoginResult::~PROTO_LoginResult() {
  // @@protoc_insertion_point(destructor:PROTO_LoginResult)
  SharedDtor(*this);
}
inline void PROTO_LoginResult::SharedDtor(MessageLite& self) {
  PROTO_LoginResult& this_ = static_cast<PROTO_LoginResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PROTO_LoginResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PROTO_LoginResult(arena);
}
constexpr auto PROTO_LoginResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PROTO_LoginResult),
                                            alignof(PROTO_LoginResult));
}
constexpr auto PROTO_LoginResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PROTO_LoginResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PROTO_LoginResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PROTO_LoginResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PROTO_LoginResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PROTO_LoginResult>(), &PROTO_LoginResult::ByteSizeLong,
              &PROTO_LoginResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_._cached_size_),
          false,
      },
      &PROTO_LoginResult::kDescriptorMethods,
      &descriptor_table_proto_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PROTO_LoginResult_class_data_ =
        PROTO_LoginResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PROTO_LoginResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PROTO_LoginResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PROTO_LoginResult_class_data_.tc_table);
  return PROTO_LoginResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2>
PROTO_LoginResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PROTO_LoginResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PROTO_LoginResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string reason = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_.reason_)}},
    // bool result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PROTO_LoginResult, _impl_.result_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool result = 1;
    {PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_.result_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string reason = 2;
    {PROTOBUF_FIELD_OFFSET(PROTO_LoginResult, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\6\0\0\0\0\0"
    "PROTO_LoginResult"
    "reason"
  }},
};
PROTOBUF_NOINLINE void PROTO_LoginResult::Clear() {
// @@protoc_insertion_point(message_clear_start:PROTO_LoginResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.reason_.ClearNonDefaultToEmpty();
  }
  _impl_.result_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PROTO_LoginResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PROTO_LoginResult& this_ = static_cast<const PROTO_LoginResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PROTO_LoginResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PROTO_LoginResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:PROTO_LoginResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool result = 1;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_result(), target);
  }

  // string reason = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_reason();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PROTO_LoginResult.reason");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PROTO_LoginResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PROTO_LoginResult::ByteSizeLong(const MessageLite& base) {
  const PROTO_LoginResult& this_ = static_cast<const PROTO_LoginResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PROTO_LoginResult::ByteSizeLong() const {
  const PROTO_LoginResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PROTO_LoginResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000002u & cached_has_bits) * 2;
   {
    // string reason = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_reason());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PROTO_LoginResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PROTO_LoginResult*>(&to_msg);
  auto& from = static_cast<const PROTO_LoginResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PROTO_LoginResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_reason(from._internal_reason());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.result_ = from._impl_.result_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PROTO_LoginResult::CopyFrom(const PROTO_LoginResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PROTO_LoginResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PROTO_LoginResult::InternalSwap(PROTO_LoginResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata PROTO_LoginResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PROTO_SyncPhysics::_Internal {
 public:
};

PROTO_SyncPhysics::PROTO_SyncPhysics(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_SyncPhysics_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PROTO_SyncPhysics)
}
PROTOBUF_NDEBUG_INLINE PROTO_SyncPhysics::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::PROTO_SyncPhysics& from_msg)
      : characters_{visibility, arena, from.characters_},
        _cached_size_{0} {}

PROTO_SyncPhysics::PROTO_SyncPhysics(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PROTO_SyncPhysics& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PROTO_SyncPhysics_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PROTO_SyncPhysics* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PROTO_SyncPhysics)
}
PROTOBUF_NDEBUG_INLINE PROTO_SyncPhysics::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : characters_{visibility, arena},
        _cached_size_{0} {}

inline void PROTO_SyncPhysics::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PROTO_SyncPhysics::~PROTO_SyncPhysics() {
  // @@protoc_insertion_point(destructor:PROTO_SyncPhysics)
  SharedDtor(*this);
}
inline void PROTO_SyncPhysics::SharedDtor(MessageLite& self) {
  PROTO_SyncPhysics& this_ = static_cast<PROTO_SyncPhysics&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PROTO_SyncPhysics::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PROTO_SyncPhysics(arena);
}
constexpr auto PROTO_SyncPhysics::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PROTO_SyncPhysics, _impl_.characters_) +
          decltype(PROTO_SyncPhysics::_impl_.characters_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PROTO_SyncPhysics), alignof(PROTO_SyncPhysics), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PROTO_SyncPhysics::PlacementNew_,
                                 sizeof(PROTO_SyncPhysics),
                                 alignof(PROTO_SyncPhysics));
  }
}
constexpr auto PROTO_SyncPhysics::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PROTO_SyncPhysics_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PROTO_SyncPhysics::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PROTO_SyncPhysics>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PROTO_SyncPhysics::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PROTO_SyncPhysics>(), &PROTO_SyncPhysics::ByteSizeLong,
              &PROTO_SyncPhysics::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PROTO_SyncPhysics, _impl_._cached_size_),
          false,
      },
      &PROTO_SyncPhysics::kDescriptorMethods,
      &descriptor_table_proto_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PROTO_SyncPhysics_class_data_ =
        PROTO_SyncPhysics::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PROTO_SyncPhysics::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PROTO_SyncPhysics_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PROTO_SyncPhysics_class_data_.tc_table);
  return PROTO_SyncPhysics_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
PROTO_SyncPhysics::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PROTO_SyncPhysics_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PROTO_SyncPhysics>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .CharacterPosition characters = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PROTO_SyncPhysics, _impl_.characters_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .CharacterPosition characters = 1;
    {PROTOBUF_FIELD_OFFSET(PROTO_SyncPhysics, _impl_.characters_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::CharacterPosition>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PROTO_SyncPhysics::Clear() {
// @@protoc_insertion_point(message_clear_start:PROTO_SyncPhysics)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.characters_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PROTO_SyncPhysics::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PROTO_SyncPhysics& this_ = static_cast<const PROTO_SyncPhysics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PROTO_SyncPhysics::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PROTO_SyncPhysics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:PROTO_SyncPhysics)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .CharacterPosition characters = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_characters_size());
       i < n; i++) {
    const auto& repfield = this_._internal_characters().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PROTO_SyncPhysics)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PROTO_SyncPhysics::ByteSizeLong(const MessageLite& base) {
  const PROTO_SyncPhysics& this_ = static_cast<const PROTO_SyncPhysics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PROTO_SyncPhysics::ByteSizeLong() const {
  const PROTO_SyncPhysics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PROTO_SyncPhysics)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .CharacterPosition characters = 1;
    {
      total_size += 1UL * this_._internal_characters_size();
      for (const auto& msg : this_._internal_characters()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PROTO_SyncPhysics::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PROTO_SyncPhysics*>(&to_msg);
  auto& from = static_cast<const PROTO_SyncPhysics&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PROTO_SyncPhysics)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_characters()->MergeFrom(
      from._internal_characters());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PROTO_SyncPhysics::CopyFrom(const PROTO_SyncPhysics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PROTO_SyncPhysics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PROTO_SyncPhysics::InternalSwap(PROTO_SyncPhysics* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.characters_.InternalSwap(&other->_impl_.characters_);
}

::google::protobuf::Metadata PROTO_SyncPhysics::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_5fmessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
