// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_message.proto
// Protobuf C++ Version: 6.31.0

#ifndef room_5fmessage_2eproto_2epb_2eh
#define room_5fmessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_room_5fmessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_room_5fmessage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_room_5fmessage_2eproto;
}  // extern "C"
enum PRM_Type : int;
extern const uint32_t PRM_Type_internal_data_[];
class PRM_RequestCreateRoom;
struct PRM_RequestCreateRoomDefaultTypeInternal;
extern PRM_RequestCreateRoomDefaultTypeInternal _PRM_RequestCreateRoom_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PRM_RequestCreateRoom_class_data_;
class PRM_RequestRoomList;
struct PRM_RequestRoomListDefaultTypeInternal;
extern PRM_RequestRoomListDefaultTypeInternal _PRM_RequestRoomList_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PRM_RequestRoomList_class_data_;
class PRM_ResultCreateRoom;
struct PRM_ResultCreateRoomDefaultTypeInternal;
extern PRM_ResultCreateRoomDefaultTypeInternal _PRM_ResultCreateRoom_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PRM_ResultCreateRoom_class_data_;
class PRM_ResultRoomList;
struct PRM_ResultRoomListDefaultTypeInternal;
extern PRM_ResultRoomListDefaultTypeInternal _PRM_ResultRoomList_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PRM_ResultRoomList_class_data_;
class PRM_RoomSmallInfo;
struct PRM_RoomSmallInfoDefaultTypeInternal;
extern PRM_RoomSmallInfoDefaultTypeInternal _PRM_RoomSmallInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PRM_RoomSmallInfo_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::PRM_Type_internal_data_>
    internal::EnumTraitsImpl::value<::PRM_Type>;
}  // namespace protobuf
}  // namespace google

enum PRM_Type : int {
  RPM_UNSPECIFIED = 0,
  CTM_REQUEST_ROOM_LIST = 1,
  STM_RESULT_ROOM_LIST = 2,
  CTM_ROOM_ENTER = 3,
  STM_ROOM_ENTER = 4,
  CTM_ROOM_LEAVE = 5,
  STM_ROOM_LEAVE = 6,
  CTM_REQUEST_CREATE_ROOM = 7,
  STM_RESULT_CREATE_ROOM = 8,
  PRM_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PRM_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PRM_Type_internal_data_[];
inline constexpr PRM_Type PRM_Type_MIN =
    static_cast<PRM_Type>(0);
inline constexpr PRM_Type PRM_Type_MAX =
    static_cast<PRM_Type>(8);
inline bool PRM_Type_IsValid(int value) {
  return 0 <= value && value <= 8;
}
inline constexpr int PRM_Type_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PRM_Type_descriptor();
template <typename T>
const ::std::string& PRM_Type_Name(T value) {
  static_assert(::std::is_same<T, PRM_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PRM_Type_Name().");
  return PRM_Type_Name(static_cast<PRM_Type>(value));
}
template <>
inline const ::std::string& PRM_Type_Name(PRM_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PRM_Type_descriptor, 0, 8>(
      static_cast<int>(value));
}
inline bool PRM_Type_Parse(
    ::absl::string_view name, PRM_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PRM_Type>(PRM_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PRM_RoomSmallInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PRM_RoomSmallInfo) */ {
 public:
  inline PRM_RoomSmallInfo() : PRM_RoomSmallInfo(nullptr) {}
  ~PRM_RoomSmallInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PRM_RoomSmallInfo* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PRM_RoomSmallInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PRM_RoomSmallInfo(::google::protobuf::internal::ConstantInitialized);

  inline PRM_RoomSmallInfo(const PRM_RoomSmallInfo& from) : PRM_RoomSmallInfo(nullptr, from) {}
  inline PRM_RoomSmallInfo(PRM_RoomSmallInfo&& from) noexcept
      : PRM_RoomSmallInfo(nullptr, ::std::move(from)) {}
  inline PRM_RoomSmallInfo& operator=(const PRM_RoomSmallInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PRM_RoomSmallInfo& operator=(PRM_RoomSmallInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PRM_RoomSmallInfo& default_instance() {
    return *reinterpret_cast<const PRM_RoomSmallInfo*>(
        &_PRM_RoomSmallInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PRM_RoomSmallInfo& a, PRM_RoomSmallInfo& b) { a.Swap(&b); }
  inline void Swap(PRM_RoomSmallInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PRM_RoomSmallInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PRM_RoomSmallInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PRM_RoomSmallInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PRM_RoomSmallInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PRM_RoomSmallInfo& from) { PRM_RoomSmallInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PRM_RoomSmallInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PRM_RoomSmallInfo"; }

 protected:
  explicit PRM_RoomSmallInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PRM_RoomSmallInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PRM_RoomSmallInfo& from);
  PRM_RoomSmallInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PRM_RoomSmallInfo&& from) noexcept
      : PRM_RoomSmallInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRoomNameFieldNumber = 2,
    kRoomIndexFieldNumber = 1,
  };
  // string roomName = 2;
  bool has_roomname() const;
  void clear_roomname() ;
  const ::std::string& roomname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_roomname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_roomname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_roomname();
  void set_allocated_roomname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_roomname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_roomname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_roomname();

  public:
  // int32 roomIndex = 1;
  bool has_roomindex() const;
  void clear_roomindex() ;
  ::int32_t roomindex() const;
  void set_roomindex(::int32_t value);

  private:
  ::int32_t _internal_roomindex() const;
  void _internal_set_roomindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PRM_RoomSmallInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PRM_RoomSmallInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr roomname_;
    ::int32_t roomindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PRM_RoomSmallInfo_class_data_;
// -------------------------------------------------------------------

class PRM_ResultCreateRoom final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PRM_ResultCreateRoom) */ {
 public:
  inline PRM_ResultCreateRoom() : PRM_ResultCreateRoom(nullptr) {}
  ~PRM_ResultCreateRoom() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PRM_ResultCreateRoom* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PRM_ResultCreateRoom));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PRM_ResultCreateRoom(::google::protobuf::internal::ConstantInitialized);

  inline PRM_ResultCreateRoom(const PRM_ResultCreateRoom& from) : PRM_ResultCreateRoom(nullptr, from) {}
  inline PRM_ResultCreateRoom(PRM_ResultCreateRoom&& from) noexcept
      : PRM_ResultCreateRoom(nullptr, ::std::move(from)) {}
  inline PRM_ResultCreateRoom& operator=(const PRM_ResultCreateRoom& from) {
    CopyFrom(from);
    return *this;
  }
  inline PRM_ResultCreateRoom& operator=(PRM_ResultCreateRoom&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PRM_ResultCreateRoom& default_instance() {
    return *reinterpret_cast<const PRM_ResultCreateRoom*>(
        &_PRM_ResultCreateRoom_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PRM_ResultCreateRoom& a, PRM_ResultCreateRoom& b) { a.Swap(&b); }
  inline void Swap(PRM_ResultCreateRoom* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PRM_ResultCreateRoom* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PRM_ResultCreateRoom* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PRM_ResultCreateRoom>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PRM_ResultCreateRoom& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PRM_ResultCreateRoom& from) { PRM_ResultCreateRoom::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PRM_ResultCreateRoom* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PRM_ResultCreateRoom"; }

 protected:
  explicit PRM_ResultCreateRoom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PRM_ResultCreateRoom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PRM_ResultCreateRoom& from);
  PRM_ResultCreateRoom(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PRM_ResultCreateRoom&& from) noexcept
      : PRM_ResultCreateRoom(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReasonFieldNumber = 2,
    kRoomIndexFieldNumber = 1,
  };
  // string reason = 2;
  bool has_reason() const;
  void clear_reason() ;
  const ::std::string& reason() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_reason(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_reason();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_reason();
  void set_allocated_reason(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_reason() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_reason();

  public:
  // int32 roomIndex = 1;
  bool has_roomindex() const;
  void clear_roomindex() ;
  ::int32_t roomindex() const;
  void set_roomindex(::int32_t value);

  private:
  ::int32_t _internal_roomindex() const;
  void _internal_set_roomindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PRM_ResultCreateRoom)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 35,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PRM_ResultCreateRoom& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr reason_;
    ::int32_t roomindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PRM_ResultCreateRoom_class_data_;
// -------------------------------------------------------------------

class PRM_RequestRoomList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PRM_RequestRoomList) */ {
 public:
  inline PRM_RequestRoomList() : PRM_RequestRoomList(nullptr) {}
  ~PRM_RequestRoomList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PRM_RequestRoomList* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PRM_RequestRoomList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PRM_RequestRoomList(::google::protobuf::internal::ConstantInitialized);

  inline PRM_RequestRoomList(const PRM_RequestRoomList& from) : PRM_RequestRoomList(nullptr, from) {}
  inline PRM_RequestRoomList(PRM_RequestRoomList&& from) noexcept
      : PRM_RequestRoomList(nullptr, ::std::move(from)) {}
  inline PRM_RequestRoomList& operator=(const PRM_RequestRoomList& from) {
    CopyFrom(from);
    return *this;
  }
  inline PRM_RequestRoomList& operator=(PRM_RequestRoomList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PRM_RequestRoomList& default_instance() {
    return *reinterpret_cast<const PRM_RequestRoomList*>(
        &_PRM_RequestRoomList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PRM_RequestRoomList& a, PRM_RequestRoomList& b) { a.Swap(&b); }
  inline void Swap(PRM_RequestRoomList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PRM_RequestRoomList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PRM_RequestRoomList* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PRM_RequestRoomList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PRM_RequestRoomList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PRM_RequestRoomList& from) { PRM_RequestRoomList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PRM_RequestRoomList* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PRM_RequestRoomList"; }

 protected:
  explicit PRM_RequestRoomList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PRM_RequestRoomList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PRM_RequestRoomList& from);
  PRM_RequestRoomList(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PRM_RequestRoomList&& from) noexcept
      : PRM_RequestRoomList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilterFieldNumber = 1,
  };
  // int32 filter = 1;
  bool has_filter() const;
  void clear_filter() ;
  ::int32_t filter() const;
  void set_filter(::int32_t value);

  private:
  ::int32_t _internal_filter() const;
  void _internal_set_filter(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PRM_RequestRoomList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PRM_RequestRoomList& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t filter_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PRM_RequestRoomList_class_data_;
// -------------------------------------------------------------------

class PRM_RequestCreateRoom final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PRM_RequestCreateRoom) */ {
 public:
  inline PRM_RequestCreateRoom() : PRM_RequestCreateRoom(nullptr) {}
  ~PRM_RequestCreateRoom() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PRM_RequestCreateRoom* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PRM_RequestCreateRoom));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PRM_RequestCreateRoom(::google::protobuf::internal::ConstantInitialized);

  inline PRM_RequestCreateRoom(const PRM_RequestCreateRoom& from) : PRM_RequestCreateRoom(nullptr, from) {}
  inline PRM_RequestCreateRoom(PRM_RequestCreateRoom&& from) noexcept
      : PRM_RequestCreateRoom(nullptr, ::std::move(from)) {}
  inline PRM_RequestCreateRoom& operator=(const PRM_RequestCreateRoom& from) {
    CopyFrom(from);
    return *this;
  }
  inline PRM_RequestCreateRoom& operator=(PRM_RequestCreateRoom&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PRM_RequestCreateRoom& default_instance() {
    return *reinterpret_cast<const PRM_RequestCreateRoom*>(
        &_PRM_RequestCreateRoom_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PRM_RequestCreateRoom& a, PRM_RequestCreateRoom& b) { a.Swap(&b); }
  inline void Swap(PRM_RequestCreateRoom* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PRM_RequestCreateRoom* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PRM_RequestCreateRoom* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PRM_RequestCreateRoom>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PRM_RequestCreateRoom& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PRM_RequestCreateRoom& from) { PRM_RequestCreateRoom::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PRM_RequestCreateRoom* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PRM_RequestCreateRoom"; }

 protected:
  explicit PRM_RequestCreateRoom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PRM_RequestCreateRoom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PRM_RequestCreateRoom& from);
  PRM_RequestCreateRoom(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PRM_RequestCreateRoom&& from) noexcept
      : PRM_RequestCreateRoom(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRoomNameFieldNumber = 1,
  };
  // string roomName = 1;
  bool has_roomname() const;
  void clear_roomname() ;
  const ::std::string& roomname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_roomname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_roomname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_roomname();
  void set_allocated_roomname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_roomname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_roomname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_roomname();

  public:
  // @@protoc_insertion_point(class_scope:PRM_RequestCreateRoom)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 38,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PRM_RequestCreateRoom& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr roomname_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PRM_RequestCreateRoom_class_data_;
// -------------------------------------------------------------------

class PRM_ResultRoomList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PRM_ResultRoomList) */ {
 public:
  inline PRM_ResultRoomList() : PRM_ResultRoomList(nullptr) {}
  ~PRM_ResultRoomList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PRM_ResultRoomList* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PRM_ResultRoomList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PRM_ResultRoomList(::google::protobuf::internal::ConstantInitialized);

  inline PRM_ResultRoomList(const PRM_ResultRoomList& from) : PRM_ResultRoomList(nullptr, from) {}
  inline PRM_ResultRoomList(PRM_ResultRoomList&& from) noexcept
      : PRM_ResultRoomList(nullptr, ::std::move(from)) {}
  inline PRM_ResultRoomList& operator=(const PRM_ResultRoomList& from) {
    CopyFrom(from);
    return *this;
  }
  inline PRM_ResultRoomList& operator=(PRM_ResultRoomList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PRM_ResultRoomList& default_instance() {
    return *reinterpret_cast<const PRM_ResultRoomList*>(
        &_PRM_ResultRoomList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PRM_ResultRoomList& a, PRM_ResultRoomList& b) { a.Swap(&b); }
  inline void Swap(PRM_ResultRoomList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PRM_ResultRoomList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PRM_ResultRoomList* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PRM_ResultRoomList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PRM_ResultRoomList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PRM_ResultRoomList& from) { PRM_ResultRoomList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PRM_ResultRoomList* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PRM_ResultRoomList"; }

 protected:
  explicit PRM_ResultRoomList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PRM_ResultRoomList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PRM_ResultRoomList& from);
  PRM_ResultRoomList(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PRM_ResultRoomList&& from) noexcept
      : PRM_ResultRoomList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kListFieldNumber = 2,
    kCountFieldNumber = 1,
  };
  // repeated .PRM_RoomSmallInfo list = 2;
  int list_size() const;
  private:
  int _internal_list_size() const;

  public:
  void clear_list() ;
  ::PRM_RoomSmallInfo* PROTOBUF_NONNULL mutable_list(int index);
  ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>* PROTOBUF_NONNULL mutable_list();

  private:
  const ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>& _internal_list() const;
  ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>* PROTOBUF_NONNULL _internal_mutable_list();
  public:
  const ::PRM_RoomSmallInfo& list(int index) const;
  ::PRM_RoomSmallInfo* PROTOBUF_NONNULL add_list();
  const ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>& list() const;
  // int32 count = 1;
  bool has_count() const;
  void clear_count() ;
  ::int32_t count() const;
  void set_count(::int32_t value);

  private:
  ::int32_t _internal_count() const;
  void _internal_set_count(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PRM_ResultRoomList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PRM_ResultRoomList& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::PRM_RoomSmallInfo > list_;
    ::int32_t count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_5fmessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PRM_ResultRoomList_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PRM_RequestRoomList

// int32 filter = 1;
inline bool PRM_RequestRoomList::has_filter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PRM_RequestRoomList::clear_filter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filter_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PRM_RequestRoomList::filter() const {
  // @@protoc_insertion_point(field_get:PRM_RequestRoomList.filter)
  return _internal_filter();
}
inline void PRM_RequestRoomList::set_filter(::int32_t value) {
  _internal_set_filter(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PRM_RequestRoomList.filter)
}
inline ::int32_t PRM_RequestRoomList::_internal_filter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filter_;
}
inline void PRM_RequestRoomList::_internal_set_filter(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filter_ = value;
}

// -------------------------------------------------------------------

// PRM_RoomSmallInfo

// int32 roomIndex = 1;
inline bool PRM_RoomSmallInfo::has_roomindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void PRM_RoomSmallInfo::clear_roomindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t PRM_RoomSmallInfo::roomindex() const {
  // @@protoc_insertion_point(field_get:PRM_RoomSmallInfo.roomIndex)
  return _internal_roomindex();
}
inline void PRM_RoomSmallInfo::set_roomindex(::int32_t value) {
  _internal_set_roomindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:PRM_RoomSmallInfo.roomIndex)
}
inline ::int32_t PRM_RoomSmallInfo::_internal_roomindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomindex_;
}
inline void PRM_RoomSmallInfo::_internal_set_roomindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = value;
}

// string roomName = 2;
inline bool PRM_RoomSmallInfo::has_roomname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PRM_RoomSmallInfo::clear_roomname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PRM_RoomSmallInfo::roomname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PRM_RoomSmallInfo.roomName)
  return _internal_roomname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PRM_RoomSmallInfo::set_roomname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.roomname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PRM_RoomSmallInfo.roomName)
}
inline ::std::string* PROTOBUF_NONNULL PRM_RoomSmallInfo::mutable_roomname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_roomname();
  // @@protoc_insertion_point(field_mutable:PRM_RoomSmallInfo.roomName)
  return _s;
}
inline const ::std::string& PRM_RoomSmallInfo::_internal_roomname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomname_.Get();
}
inline void PRM_RoomSmallInfo::_internal_set_roomname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.roomname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PRM_RoomSmallInfo::_internal_mutable_roomname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.roomname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PRM_RoomSmallInfo::release_roomname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PRM_RoomSmallInfo.roomName)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.roomname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.roomname_.Set("", GetArena());
  }
  return released;
}
inline void PRM_RoomSmallInfo::set_allocated_roomname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.roomname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomname_.IsDefault()) {
    _impl_.roomname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PRM_RoomSmallInfo.roomName)
}

// -------------------------------------------------------------------

// PRM_ResultRoomList

// int32 count = 1;
inline bool PRM_ResultRoomList::has_count() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PRM_ResultRoomList::clear_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PRM_ResultRoomList::count() const {
  // @@protoc_insertion_point(field_get:PRM_ResultRoomList.count)
  return _internal_count();
}
inline void PRM_ResultRoomList::set_count(::int32_t value) {
  _internal_set_count(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:PRM_ResultRoomList.count)
}
inline ::int32_t PRM_ResultRoomList::_internal_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_;
}
inline void PRM_ResultRoomList::_internal_set_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = value;
}

// repeated .PRM_RoomSmallInfo list = 2;
inline int PRM_ResultRoomList::_internal_list_size() const {
  return _internal_list().size();
}
inline int PRM_ResultRoomList::list_size() const {
  return _internal_list_size();
}
inline void PRM_ResultRoomList::clear_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_.Clear();
}
inline ::PRM_RoomSmallInfo* PROTOBUF_NONNULL PRM_ResultRoomList::mutable_list(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PRM_ResultRoomList.list)
  return _internal_mutable_list()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>* PROTOBUF_NONNULL PRM_ResultRoomList::mutable_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PRM_ResultRoomList.list)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_list();
}
inline const ::PRM_RoomSmallInfo& PRM_ResultRoomList::list(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PRM_ResultRoomList.list)
  return _internal_list().Get(index);
}
inline ::PRM_RoomSmallInfo* PROTOBUF_NONNULL PRM_ResultRoomList::add_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::PRM_RoomSmallInfo* _add = _internal_mutable_list()->Add();
  // @@protoc_insertion_point(field_add:PRM_ResultRoomList.list)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>& PRM_ResultRoomList::list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PRM_ResultRoomList.list)
  return _internal_list();
}
inline const ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>&
PRM_ResultRoomList::_internal_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.list_;
}
inline ::google::protobuf::RepeatedPtrField<::PRM_RoomSmallInfo>* PROTOBUF_NONNULL
PRM_ResultRoomList::_internal_mutable_list() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.list_;
}

// -------------------------------------------------------------------

// PRM_RequestCreateRoom

// string roomName = 1;
inline bool PRM_RequestCreateRoom::has_roomname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PRM_RequestCreateRoom::clear_roomname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PRM_RequestCreateRoom::roomname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PRM_RequestCreateRoom.roomName)
  return _internal_roomname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PRM_RequestCreateRoom::set_roomname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.roomname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PRM_RequestCreateRoom.roomName)
}
inline ::std::string* PROTOBUF_NONNULL PRM_RequestCreateRoom::mutable_roomname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_roomname();
  // @@protoc_insertion_point(field_mutable:PRM_RequestCreateRoom.roomName)
  return _s;
}
inline const ::std::string& PRM_RequestCreateRoom::_internal_roomname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomname_.Get();
}
inline void PRM_RequestCreateRoom::_internal_set_roomname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.roomname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PRM_RequestCreateRoom::_internal_mutable_roomname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.roomname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PRM_RequestCreateRoom::release_roomname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PRM_RequestCreateRoom.roomName)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.roomname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.roomname_.Set("", GetArena());
  }
  return released;
}
inline void PRM_RequestCreateRoom::set_allocated_roomname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.roomname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomname_.IsDefault()) {
    _impl_.roomname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PRM_RequestCreateRoom.roomName)
}

// -------------------------------------------------------------------

// PRM_ResultCreateRoom

// int32 roomIndex = 1;
inline bool PRM_ResultCreateRoom::has_roomindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void PRM_ResultCreateRoom::clear_roomindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t PRM_ResultCreateRoom::roomindex() const {
  // @@protoc_insertion_point(field_get:PRM_ResultCreateRoom.roomIndex)
  return _internal_roomindex();
}
inline void PRM_ResultCreateRoom::set_roomindex(::int32_t value) {
  _internal_set_roomindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:PRM_ResultCreateRoom.roomIndex)
}
inline ::int32_t PRM_ResultCreateRoom::_internal_roomindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomindex_;
}
inline void PRM_ResultCreateRoom::_internal_set_roomindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomindex_ = value;
}

// string reason = 2;
inline bool PRM_ResultCreateRoom::has_reason() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void PRM_ResultCreateRoom::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PRM_ResultCreateRoom::reason() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PRM_ResultCreateRoom.reason)
  return _internal_reason();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PRM_ResultCreateRoom::set_reason(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reason_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PRM_ResultCreateRoom.reason)
}
inline ::std::string* PROTOBUF_NONNULL PRM_ResultCreateRoom::mutable_reason()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:PRM_ResultCreateRoom.reason)
  return _s;
}
inline const ::std::string& PRM_ResultCreateRoom::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reason_.Get();
}
inline void PRM_ResultCreateRoom::_internal_set_reason(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reason_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PRM_ResultCreateRoom::_internal_mutable_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.reason_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PRM_ResultCreateRoom::release_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PRM_ResultCreateRoom.reason)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.reason_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.reason_.Set("", GetArena());
  }
  return released;
}
inline void PRM_ResultCreateRoom::set_allocated_reason(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reason_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PRM_ResultCreateRoom.reason)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::PRM_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::PRM_Type>() {
  return ::PRM_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // room_5fmessage_2eproto_2epb_2eh
