# Isolation 서버 도커 이미지 빌드 스크립트
# 빌드시 bdocker.sh를 실행하라

# exit 상태 container 제거
# docker container prune

# 특정 라인부터 캐시를 무효화 하고 싶다면 해당 라인에 ARG CACHEBUST=1 을 넣고
# 명령어 옵션에 --build-arg CACHEBUST=$(date +%s) 을 추가한다

# --progress=plain 옵션으로 모든 로그를 출력
# --no-cache 이전에 빌드한 캐시를 무시하고 전체 재빌드

ARG DEBIAN_FRONTEND=noninteractive
ARG SERVER_NAME=isolation-server
ARG REDIS_SERVER_HOST=redis
ARG REDIS_SERVER_PORT=6379

# 서버 프로그램 빌드용 스테이지 ==============================================================
FROM ubuntu:24.04 AS builder

ARG DEBIAN_FRONTEND
ARG PROTOBUF_VERSION=31.0
ARG SERVER_NAME
ARG REDIS_SERVER_HOST
ARG REDIS_SERVER_PORT

# nodejs 최신 LTS 버전 저장소 등록
#RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - 

# 기본 필수 개발 도구 및 CMake, 빌드 시스템 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    curl \
    unzip \
    git \
    ca-certificates \
    libboost-all-dev \
    libhiredis-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Protocol Buffers protoc 설치
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip \
    && unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local \
    && rm protoc-${PROTOBUF_VERSION}-linux-x86_64.zip

# Protocol Buffers 설치
WORKDIR /tmp/protobuf
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-${PROTOBUF_VERSION}.tar.gz \
    && tar -xzf protobuf-${PROTOBUF_VERSION}.tar.gz \
    && cd protobuf-${PROTOBUF_VERSION} \
    && cmake -B build -Dprotobuf_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF \
    && cmake --build build -j$(nproc) \
    && cmake --install build \
    && cd /tmp && rm -rf protobuf-${PROTOBUF_VERSION}

# redis++ 설치
# --depth 1: repository 전체 기록 대신 가장 최근의 커밋 하나만 가져옴. 과거 수정 이력, 커밋 로그 제외해서 용량 감소
WORKDIR /tmp
RUN git clone --branch 1.3.15 --depth 1 https://github.com/sewenew/redis-plus-plus.git \
    && cd redis-plus-plus \
    && cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DREDIS_PLUS_PLUS_BUILD_TEST=OFF \
        -DREDIS_PLUS_PLUS_BUILD_EXAMPLES=OFF \
    && cmake --build build -j$(nproc) \
    && cmake --install build \
    && cd /tmp \
    && rm -rf redis-plus-plus

WORKDIR /$SERVER_NAME-build

# 캐시 무효화
ARG CACHEBUST=1

COPY . .

# 서버 프로그램 빌드
RUN sh build.sh $SERVER_NAME $REDIS_SERVER_HOST $REDIS_SERVER_PORT
    
# Github workflow 테스트를 위한 nodejs 캐싱용 스테이지 ==============================================================
FROM ubuntu:24.04 AS package-cache

ARG DEBIAN_FRONTEND

RUN curl -fsSL https://deb.nodesource.com/setup_26.x | bash - 

RUN apt-get update && apt-get install -y --no-install-recommends \
    nodejs \
    libhiredis1.1.0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 서버 프로그램 실행환경 구축 스테이지 ==============================================================
FROM package-cache AS runner

# 캐시 무효화
ARG CACHEBUST=1
ARG SERVER_NAME
ENV SERVER_NAME_ENV=$SERVER_NAME

WORKDIR /isolation-server

COPY --from=builder /${SERVER_NAME}-build/build/${SERVER_NAME}-app .

ENTRYPOINT ["sh", "-c", "exec ./${SERVER_NAME_ENV}-app"]